/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Activities extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord> {

	private static final long serialVersionUID = 1223238634;

	/**
	 * The reference instance of <code>core.activities</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Activities ACTIVITIES = new com.sonicle.webtop.core.jooq.core.tables.Activities();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord.class;
	}

	/**
	 * The column <code>core.activities.activity_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord, java.lang.Integer> ACTIVITY_ID = createField("activity_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>core.activities.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>core.activities.user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>core.activities.revision_status</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord, java.lang.String> REVISION_STATUS = createField("revision_status", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>core.activities.description</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.activities.read_only</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord, java.lang.Boolean> READ_ONLY = createField("read_only", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>core.activities.external_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord, java.lang.String> EXTERNAL_ID = createField("external_id", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>core.activities</code> table reference
	 */
	public Activities() {
		this("activities", null);
	}

	/**
	 * Create an aliased <code>core.activities</code> table reference
	 */
	public Activities(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.Activities.ACTIVITIES);
	}

	private Activities(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Activities(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.core.jooq.core.Keys.IDENTITY_ACTIVITIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.ACTIVITIES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.ACTIVITIES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.Activities as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.Activities(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.Activities rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.Activities(name, null);
	}
}
