/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomersDeprecated extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord> {

	private static final long serialVersionUID = 1630637984;

	/**
	 * The reference instance of <code>core.customers_deprecated</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.CustomersDeprecated CUSTOMERS_DEPRECATED = new com.sonicle.webtop.core.jooq.core.tables.CustomersDeprecated();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord.class;
	}

	/**
	 * The column <code>core.customers_deprecated.customer_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> CUSTOMER_ID = createField("customer_id", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

	/**
	 * The column <code>core.customers_deprecated.description</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>core.customers_deprecated.type</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

	/**
	 * The column <code>core.customers_deprecated.address</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>core.customers_deprecated.city</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>core.customers_deprecated.state</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>core.customers_deprecated.postalcode</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> POSTALCODE = createField("postalcode", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>core.customers_deprecated.country</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>core.customers_deprecated.telephone</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>core.customers_deprecated.email</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(80), this, "");

	/**
	 * The column <code>core.customers_deprecated.from_drm</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> FROM_DRM = createField("from_drm", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

	/**
	 * The column <code>core.customers_deprecated.parent_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>core.customers_deprecated.external_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> EXTERNAL_ID = createField("external_id", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>core.customers_deprecated.status</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

	/**
	 * The column <code>core.customers_deprecated.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>core.customers_deprecated.km</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> KM = createField("km", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>core.customers_deprecated.lock</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> LOCK = createField("lock", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>core.customers_deprecated.note</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord, java.lang.String> NOTE = createField("note", org.jooq.impl.SQLDataType.VARCHAR.length(2000), this, "");

	/**
	 * Create a <code>core.customers_deprecated</code> table reference
	 */
	public CustomersDeprecated() {
		this("customers_deprecated", null);
	}

	/**
	 * Create an aliased <code>core.customers_deprecated</code> table reference
	 */
	public CustomersDeprecated(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.CustomersDeprecated.CUSTOMERS_DEPRECATED);
	}

	private CustomersDeprecated(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord> aliased) {
		this(alias, aliased, null);
	}

	private CustomersDeprecated(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.CUSTOMERS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.CustomersDeprecatedRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.CUSTOMERS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.CustomersDeprecated as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.CustomersDeprecated(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.CustomersDeprecated rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.CustomersDeprecated(name, null);
	}
}
