/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DomainSettings extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord> {

	private static final long serialVersionUID = -1141053041;

	/**
	 * The reference instance of <code>core.domain_settings</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.DomainSettings DOMAIN_SETTINGS = new com.sonicle.webtop.core.jooq.core.tables.DomainSettings();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord.class;
	}

	/**
	 * The column <code>core.domain_settings.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>core.domain_settings.service_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord, java.lang.String> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.domain_settings.key</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord, java.lang.String> KEY = createField("key", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.domain_settings.value</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>core.domain_settings</code> table reference
	 */
	public DomainSettings() {
		this("domain_settings", null);
	}

	/**
	 * Create an aliased <code>core.domain_settings</code> table reference
	 */
	public DomainSettings(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.DomainSettings.DOMAIN_SETTINGS);
	}

	private DomainSettings(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord> aliased) {
		this(alias, aliased, null);
	}

	private DomainSettings(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.DOMAIN_SETTINGS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.DomainSettingsRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.DOMAIN_SETTINGS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.DomainSettings as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.DomainSettings(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.DomainSettings rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.DomainSettings(name, null);
	}
}
