/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileTypes extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord> {

	private static final long serialVersionUID = -1026262814;

	/**
	 * The reference instance of <code>core.file_types</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.FileTypes FILE_TYPES = new com.sonicle.webtop.core.jooq.core.tables.FileTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord.class;
	}

	/**
	 * The column <code>core.file_types.extension</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord, java.lang.String> EXTENSION = createField("extension", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.file_types.type</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.file_types.subtype</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord, java.lang.String> SUBTYPE = createField("subtype", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>core.file_types</code> table reference
	 */
	public FileTypes() {
		this("file_types", null);
	}

	/**
	 * Create an aliased <code>core.file_types</code> table reference
	 */
	public FileTypes(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.FileTypes.FILE_TYPES);
	}

	private FileTypes(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private FileTypes(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.FILE_TYPES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.FILE_TYPES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.FileTypes as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.FileTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.FileTypes rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.FileTypes(name, null);
	}
}
