/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImHistoryMessages extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord> {

	private static final long serialVersionUID = -992727632;

	/**
	 * The reference instance of <code>core.im_history_messages</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.ImHistoryMessages IM_HISTORY_MESSAGES = new com.sonicle.webtop.core.jooq.core.tables.ImHistoryMessages();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord.class;
	}

	/**
	 * The column <code>core.im_history_messages.id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>core.im_history_messages.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>core.im_history_messages.user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>core.im_history_messages.chat_jid</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, java.lang.String> CHAT_JID = createField("chat_jid", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.im_history_messages.sender_jid</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, java.lang.String> SENDER_JID = createField("sender_jid", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.im_history_messages.sender_resource</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, java.lang.String> SENDER_RESOURCE = createField("sender_resource", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>core.im_history_messages.date</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, org.joda.time.LocalDate> DATE = createField("date", org.jooq.impl.SQLDataType.DATE, this, "", new com.sonicle.webtop.core.jooq.LocalDateConverter());

	/**
	 * The column <code>core.im_history_messages.timestamp</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, org.joda.time.DateTime> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new com.sonicle.webtop.core.jooq.DateTimeConverter());

	/**
	 * The column <code>core.im_history_messages.action</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, java.lang.String> ACTION = createField("action", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * The column <code>core.im_history_messages.text</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>core.im_history_messages.message_uid</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, java.lang.String> MESSAGE_UID = createField("message_uid", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.im_history_messages.stanza_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, java.lang.String> STANZA_ID = createField("stanza_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>core.im_history_messages</code> table reference
	 */
	public ImHistoryMessages() {
		this("im_history_messages", null);
	}

	/**
	 * Create an aliased <code>core.im_history_messages</code> table reference
	 */
	public ImHistoryMessages(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.ImHistoryMessages.IM_HISTORY_MESSAGES);
	}

	private ImHistoryMessages(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ImHistoryMessages(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.core.jooq.core.Keys.IDENTITY_IM_HISTORY_MESSAGES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.IM_HISTORY_MESSAGES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.ImHistoryMessagesRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.IM_HISTORY_MESSAGES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.ImHistoryMessages as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.ImHistoryMessages(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.ImHistoryMessages rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.ImHistoryMessages(name, null);
	}
}
