/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Languages extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.LanguagesRecord> {

	private static final long serialVersionUID = 1521138272;

	/**
	 * The reference instance of <code>core.languages</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Languages LANGUAGES = new com.sonicle.webtop.core.jooq.core.tables.Languages();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.LanguagesRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.LanguagesRecord.class;
	}

	/**
	 * The column <code>core.languages.language_tag</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.LanguagesRecord, java.lang.String> LANGUAGE_TAG = createField("language_tag", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "");

	/**
	 * Create a <code>core.languages</code> table reference
	 */
	public Languages() {
		this("languages", null);
	}

	/**
	 * Create an aliased <code>core.languages</code> table reference
	 */
	public Languages(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.Languages.LANGUAGES);
	}

	private Languages(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.LanguagesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Languages(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.LanguagesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.LanguagesRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.LANGUAGES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.LanguagesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.LanguagesRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.LANGUAGES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.Languages as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.Languages(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.Languages rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.Languages(name, null);
	}
}
