/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord> {

	private static final long serialVersionUID = -909902213;

	/**
	 * The reference instance of <code>core.roles</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Roles ROLES = new com.sonicle.webtop.core.jooq.core.tables.Roles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord.class;
	}

	/**
	 * The column <code>core.roles.role_uid</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord, java.lang.String> ROLE_UID = createField("role_uid", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>core.roles.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>core.roles.name</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>core.roles.description</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>core.roles</code> table reference
	 */
	public Roles() {
		this("roles", null);
	}

	/**
	 * Create an aliased <code>core.roles</code> table reference
	 */
	public Roles(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.Roles.ROLES);
	}

	private Roles(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Roles(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.ROLES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.RolesRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.ROLES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.Roles as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.Roles(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.Roles rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.Roles(name, null);
	}
}
