/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesPermissions extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord> {

	private static final long serialVersionUID = -1335575743;

	/**
	 * The reference instance of <code>core.roles_permissions</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.RolesPermissions ROLES_PERMISSIONS = new com.sonicle.webtop.core.jooq.core.tables.RolesPermissions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord.class;
	}

	/**
	 * The column <code>core.roles_permissions.role_permission_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord, java.lang.Integer> ROLE_PERMISSION_ID = createField("role_permission_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>core.roles_permissions.role_uid</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord, java.lang.String> ROLE_UID = createField("role_uid", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>core.roles_permissions.service_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord, java.lang.String> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.roles_permissions.key</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord, java.lang.String> KEY = createField("key", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.roles_permissions.action</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord, java.lang.String> ACTION = createField("action", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.roles_permissions.instance</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord, java.lang.String> INSTANCE = createField("instance", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>core.roles_permissions</code> table reference
	 */
	public RolesPermissions() {
		this("roles_permissions", null);
	}

	/**
	 * Create an aliased <code>core.roles_permissions</code> table reference
	 */
	public RolesPermissions(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.RolesPermissions.ROLES_PERMISSIONS);
	}

	private RolesPermissions(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private RolesPermissions(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.core.jooq.core.Keys.IDENTITY_ROLES_PERMISSIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.RolesPermissions as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.RolesPermissions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.RolesPermissions rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.RolesPermissions(name, null);
	}
}
