/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServicestoreEntries extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord> {

	private static final long serialVersionUID = 560484875;

	/**
	 * The reference instance of <code>core.servicestore_entries</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries SERVICESTORE_ENTRIES = new com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord.class;
	}

	/**
	 * The column <code>core.servicestore_entries.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>core.servicestore_entries.user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>core.servicestore_entries.service_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord, java.lang.String> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.servicestore_entries.context</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord, java.lang.String> CONTEXT = createField("context", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>core.servicestore_entries.key</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord, java.lang.String> KEY = createField("key", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * The column <code>core.servicestore_entries.value</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * The column <code>core.servicestore_entries.frequency</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord, java.lang.Integer> FREQUENCY = createField("frequency", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>core.servicestore_entries.last_update</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord, org.joda.time.DateTime> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new com.sonicle.webtop.core.jooq.DateTimeConverter());

	/**
	 * Create a <code>core.servicestore_entries</code> table reference
	 */
	public ServicestoreEntries() {
		this("servicestore_entries", null);
	}

	/**
	 * Create an aliased <code>core.servicestore_entries</code> table reference
	 */
	public ServicestoreEntries(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES);
	}

	private ServicestoreEntries(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ServicestoreEntries(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.SERVICESTORE_ENTRIES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.SERVICESTORE_ENTRIES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries(name, null);
	}
}
