/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Settings extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.SettingsRecord> {

	private static final long serialVersionUID = 1382596340;

	/**
	 * The reference instance of <code>core.settings</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Settings SETTINGS = new com.sonicle.webtop.core.jooq.core.tables.Settings();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.SettingsRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.SettingsRecord.class;
	}

	/**
	 * The column <code>core.settings.service_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.SettingsRecord, java.lang.String> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.settings.key</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.SettingsRecord, java.lang.String> KEY = createField("key", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.settings.value</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.SettingsRecord, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>core.settings</code> table reference
	 */
	public Settings() {
		this("settings", null);
	}

	/**
	 * Create an aliased <code>core.settings</code> table reference
	 */
	public Settings(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.Settings.SETTINGS);
	}

	private Settings(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.SettingsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Settings(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.SettingsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.SettingsRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.SETTINGS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.SettingsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.SettingsRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.SETTINGS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.Settings as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.Settings(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.Settings rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.Settings(name, null);
	}
}
