/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsDb extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord> {

	private static final long serialVersionUID = -178201848;

	/**
	 * The reference instance of <code>core.settings_db</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.SettingsDb SETTINGS_DB = new com.sonicle.webtop.core.jooq.core.tables.SettingsDb();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord.class;
	}

	/**
	 * The column <code>core.settings_db.service_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord, java.lang.String> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.settings_db.key</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord, java.lang.String> KEY = createField("key", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.settings_db.is_system</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord, java.lang.Boolean> IS_SYSTEM = createField("is_system", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>core.settings_db.is_domain</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord, java.lang.Boolean> IS_DOMAIN = createField("is_domain", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>core.settings_db.is_user</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord, java.lang.Boolean> IS_USER = createField("is_user", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>core.settings_db.hidden</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord, java.lang.Boolean> HIDDEN = createField("hidden", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>core.settings_db.type</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>core.settings_db.help</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord, java.lang.String> HELP = createField("help", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>core.settings_db</code> table reference
	 */
	public SettingsDb() {
		this("settings_db", null);
	}

	/**
	 * Create an aliased <code>core.settings_db</code> table reference
	 */
	public SettingsDb(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB);
	}

	private SettingsDb(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord> aliased) {
		this(alias, aliased, null);
	}

	private SettingsDb(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.SETTINGS_DB_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.SETTINGS_DB_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.SettingsDb as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.SettingsDb(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.SettingsDb rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.SettingsDb(name, null);
	}
}
