/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.TestRecord> {

	private static final long serialVersionUID = 1460348866;

	/**
	 * The reference instance of <code>core.test</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Test TEST = new com.sonicle.webtop.core.jooq.core.tables.Test();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.TestRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.TestRecord.class;
	}

	/**
	 * The column <code>core.test.id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.TestRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>core.test</code> table reference
	 */
	public Test() {
		this("test", null);
	}

	/**
	 * Create an aliased <code>core.test</code> table reference
	 */
	public Test(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.Test.TEST);
	}

	private Test(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.TestRecord> aliased) {
		this(alias, aliased, null);
	}

	private Test(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.TestRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.TestRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.TEST_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.TestRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.TestRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.TEST_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.Test as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.Test(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.Test rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.Test(name, null);
	}
}
