/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpgradeStatements extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord> {

	private static final long serialVersionUID = 1410181367;

	/**
	 * The reference instance of <code>core.upgrade_statements</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements UPGRADE_STATEMENTS = new com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord.class;
	}

	/**
	 * The column <code>core.upgrade_statements.upgrade_statement_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, java.lang.Integer> UPGRADE_STATEMENT_ID = createField("upgrade_statement_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>core.upgrade_statements.tag</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, java.lang.String> TAG = createField("tag", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>core.upgrade_statements.service_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, java.lang.String> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.upgrade_statements.sequence_no</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, java.lang.Short> SEQUENCE_NO = createField("sequence_no", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>core.upgrade_statements.script_name</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, java.lang.String> SCRIPT_NAME = createField("script_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.upgrade_statements.statement_type</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, java.lang.String> STATEMENT_TYPE = createField("statement_type", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * The column <code>core.upgrade_statements.statement_data_source</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, java.lang.String> STATEMENT_DATA_SOURCE = createField("statement_data_source", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>core.upgrade_statements.statement_body</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, java.lang.String> STATEMENT_BODY = createField("statement_body", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>core.upgrade_statements.run_status</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, java.lang.String> RUN_STATUS = createField("run_status", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>core.upgrade_statements.run_timestamp</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, org.joda.time.DateTime> RUN_TIMESTAMP = createField("run_timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new com.sonicle.webtop.core.jooq.DateTimeConverter());

	/**
	 * The column <code>core.upgrade_statements.run_message</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, java.lang.String> RUN_MESSAGE = createField("run_message", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>core.upgrade_statements</code> table reference
	 */
	public UpgradeStatements() {
		this("upgrade_statements", null);
	}

	/**
	 * Create an aliased <code>core.upgrade_statements</code> table reference
	 */
	public UpgradeStatements(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS);
	}

	private UpgradeStatements(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord> aliased) {
		this(alias, aliased, null);
	}

	private UpgradeStatements(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.core.jooq.core.Keys.IDENTITY_UPGRADE_STATEMENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.UPGRADE_STATEMENTS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.UPGRADE_STATEMENTS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements(name, null);
	}
}
