/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSettings extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord> {

	private static final long serialVersionUID = 2079267809;

	/**
	 * The reference instance of <code>core.user_settings</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.UserSettings USER_SETTINGS = new com.sonicle.webtop.core.jooq.core.tables.UserSettings();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord.class;
	}

	/**
	 * The column <code>core.user_settings.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>core.user_settings.user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>core.user_settings.service_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord, java.lang.String> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.user_settings.key</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord, java.lang.String> KEY = createField("key", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>core.user_settings.value</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>core.user_settings</code> table reference
	 */
	public UserSettings() {
		this("user_settings", null);
	}

	/**
	 * Create an aliased <code>core.user_settings</code> table reference
	 */
	public UserSettings(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.UserSettings.USER_SETTINGS);
	}

	private UserSettings(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserSettings(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.USER_SETTINGS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.UserSettingsRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.USER_SETTINGS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.UserSettings as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.UserSettings(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.UserSettings rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.UserSettings(name, null);
	}
}
