/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersInfo extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord> {

	private static final long serialVersionUID = -202690242;

	/**
	 * The reference instance of <code>core.users_info</code>
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.UsersInfo USERS_INFO = new com.sonicle.webtop.core.jooq.core.tables.UsersInfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord.class;
	}

	/**
	 * The column <code>core.users_info.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>core.users_info.user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>core.users_info.searchfield</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> SEARCHFIELD = createField("searchfield", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>core.users_info.title</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>core.users_info.first_name</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(60), this, "");

	/**
	 * The column <code>core.users_info.last_name</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(60), this, "");

	/**
	 * The column <code>core.users_info.nickname</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> NICKNAME = createField("nickname", org.jooq.impl.SQLDataType.VARCHAR.length(60), this, "");

	/**
	 * The column <code>core.users_info.gender</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR.length(6), this, "");

	/**
	 * The column <code>core.users_info.email</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(320), this, "");

	/**
	 * The column <code>core.users_info.telephone</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>core.users_info.fax</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> FAX = createField("fax", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>core.users_info.pager</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> PAGER = createField("pager", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>core.users_info.mobile</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> MOBILE = createField("mobile", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>core.users_info.address</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>core.users_info.city</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>core.users_info.postal_code</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> POSTAL_CODE = createField("postal_code", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>core.users_info.state</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>core.users_info.country</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>core.users_info.company</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> COMPANY = createField("company", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>core.users_info.function</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> FUNCTION = createField("function", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>core.users_info.custom1</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> CUSTOM1 = createField("custom1", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>core.users_info.custom2</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> CUSTOM2 = createField("custom2", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>core.users_info.custom3</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord, java.lang.String> CUSTOM3 = createField("custom3", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>core.users_info</code> table reference
	 */
	public UsersInfo() {
		this("users_info", null);
	}

	/**
	 * Create an aliased <code>core.users_info</code> table reference
	 */
	public UsersInfo(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.core.tables.UsersInfo.USERS_INFO);
	}

	private UsersInfo(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private UsersInfo(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.core.Core.CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.core.Keys.USERS_INFO_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.core.tables.records.UsersInfoRecord>>asList(com.sonicle.webtop.core.jooq.core.Keys.USERS_INFO_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.core.tables.UsersInfo as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.core.tables.UsersInfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.core.tables.UsersInfo rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.core.tables.UsersInfo(name, null);
	}
}
