/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.config.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FetchmailPolls extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord> {

	private static final long serialVersionUID = 1714128519;

	/**
	 * The reference instance of <code>config.fetchmail_polls</code>
	 */
	public static final com.sonicle.webtop.core.jooq.config.tables.FetchmailPolls FETCHMAIL_POLLS = new com.sonicle.webtop.core.jooq.config.tables.FetchmailPolls();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord.class;
	}

	/**
	 * The column <code>config.fetchmail_polls.poll_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord, java.lang.Integer> POLL_ID = createField("poll_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>config.fetchmail_polls.context</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord, java.lang.String> CONTEXT = createField("context", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>config.fetchmail_polls.host</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord, java.lang.String> HOST = createField("host", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>config.fetchmail_polls.port</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord, java.lang.Short> PORT = createField("port", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>config.fetchmail_polls.protocol</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord, java.lang.String> PROTOCOL = createField("protocol", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * The column <code>config.fetchmail_polls.ssl</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord, java.lang.Boolean> SSL = createField("ssl", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>config.fetchmail_polls.remote_user</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord, java.lang.String> REMOTE_USER = createField("remote_user", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>config.fetchmail_polls.remote_password</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord, java.lang.String> REMOTE_PASSWORD = createField("remote_password", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>config.fetchmail_polls.local_user</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord, java.lang.String> LOCAL_USER = createField("local_user", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>config.fetchmail_polls</code> table reference
	 */
	public FetchmailPolls() {
		this("fetchmail_polls", null);
	}

	/**
	 * Create an aliased <code>config.fetchmail_polls</code> table reference
	 */
	public FetchmailPolls(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.config.tables.FetchmailPolls.FETCHMAIL_POLLS);
	}

	private FetchmailPolls(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord> aliased) {
		this(alias, aliased, null);
	}

	private FetchmailPolls(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.config.Config.CONFIG, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.core.jooq.config.Keys.IDENTITY_FETCHMAIL_POLLS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.config.Keys.FETCHMAIL_POLLS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.config.tables.records.FetchmailPollsRecord>>asList(com.sonicle.webtop.core.jooq.config.Keys.FETCHMAIL_POLLS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.config.tables.FetchmailPolls as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.config.tables.FetchmailPolls(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.config.tables.FetchmailPolls rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.config.tables.FetchmailPolls(name, null);
	}
}
