/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.config.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PecbridgeFetchers extends org.jooq.impl.TableImpl<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord> {

	private static final long serialVersionUID = -713440685;

	/**
	 * The reference instance of <code>config.pecbridge_fetchers</code>
	 */
	public static final com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers PECBRIDGE_FETCHERS = new com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord> getRecordType() {
		return com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord.class;
	}

	/**
	 * The column <code>config.pecbridge_fetchers.fetcher_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord, java.lang.Integer> FETCHER_ID = createField("fetcher_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>config.pecbridge_fetchers.context</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord, java.lang.String> CONTEXT = createField("context", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>config.pecbridge_fetchers.forward_address</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord, java.lang.String> FORWARD_ADDRESS = createField("forward_address", org.jooq.impl.SQLDataType.VARCHAR.length(320), this, "");

	/**
	 * The column <code>config.pecbridge_fetchers.delete_on_forward</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord, java.lang.Boolean> DELETE_ON_FORWARD = createField("delete_on_forward", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>config.pecbridge_fetchers.host</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord, java.lang.String> HOST = createField("host", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>config.pecbridge_fetchers.port</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord, java.lang.Short> PORT = createField("port", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>config.pecbridge_fetchers.protocol</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord, java.lang.String> PROTOCOL = createField("protocol", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * The column <code>config.pecbridge_fetchers.username</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>config.pecbridge_fetchers.password</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>config.pecbridge_fetchers.webtop_profile_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord, java.lang.String> WEBTOP_PROFILE_ID = createField("webtop_profile_id", org.jooq.impl.SQLDataType.VARCHAR.length(150), this, "");

	/**
	 * Create a <code>config.pecbridge_fetchers</code> table reference
	 */
	public PecbridgeFetchers() {
		this("pecbridge_fetchers", null);
	}

	/**
	 * Create an aliased <code>config.pecbridge_fetchers</code> table reference
	 */
	public PecbridgeFetchers(java.lang.String alias) {
		this(alias, com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS);
	}

	private PecbridgeFetchers(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord> aliased) {
		this(alias, aliased, null);
	}

	private PecbridgeFetchers(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.core.jooq.config.Config.CONFIG, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.core.jooq.config.Keys.IDENTITY_PECBRIDGE_FETCHERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord> getPrimaryKey() {
		return com.sonicle.webtop.core.jooq.config.Keys.PECBRIDGE_FETCHERS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord>>asList(com.sonicle.webtop.core.jooq.config.Keys.PECBRIDGE_FETCHERS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers as(java.lang.String alias) {
		return new com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers rename(java.lang.String name) {
		return new com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers(name, null);
	}
}
