/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core;

/**
 * Convenience access to all tables in core
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table core.____customers
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.____Customers ____CUSTOMERS = com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS;

	/**
	 * The table core.activities
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Activities ACTIVITIES = com.sonicle.webtop.core.jooq.core.tables.Activities.ACTIVITIES;

	/**
	 * The table core.autosave
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Autosave AUTOSAVE = com.sonicle.webtop.core.jooq.core.tables.Autosave.AUTOSAVE;

	/**
	 * The table core.causals
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Causals CAUSALS = com.sonicle.webtop.core.jooq.core.tables.Causals.CAUSALS;

	/**
	 * The table core.customers_deprecated
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.CustomersDeprecated CUSTOMERS_DEPRECATED = com.sonicle.webtop.core.jooq.core.tables.CustomersDeprecated.CUSTOMERS_DEPRECATED;

	/**
	 * The table core.domain_settings
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.DomainSettings DOMAIN_SETTINGS = com.sonicle.webtop.core.jooq.core.tables.DomainSettings.DOMAIN_SETTINGS;

	/**
	 * The table core.domains
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Domains DOMAINS = com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS;

	/**
	 * The table core.file_types
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.FileTypes FILE_TYPES = com.sonicle.webtop.core.jooq.core.tables.FileTypes.FILE_TYPES;

	/**
	 * The table core.im_chats
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.ImChats IM_CHATS = com.sonicle.webtop.core.jooq.core.tables.ImChats.IM_CHATS;

	/**
	 * The table core.im_messages
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.ImMessages IM_MESSAGES = com.sonicle.webtop.core.jooq.core.tables.ImMessages.IM_MESSAGES;

	/**
	 * The table core.languages
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Languages LANGUAGES = com.sonicle.webtop.core.jooq.core.tables.Languages.LANGUAGES;

	/**
	 * The table core.local_vault
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.LocalVault LOCAL_VAULT = com.sonicle.webtop.core.jooq.core.tables.LocalVault.LOCAL_VAULT;

	/**
	 * The table core.master_data
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.MasterData MASTER_DATA = com.sonicle.webtop.core.jooq.core.tables.MasterData.MASTER_DATA;

	/**
	 * The table core.media_types
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.MediaTypes MEDIA_TYPES = com.sonicle.webtop.core.jooq.core.tables.MediaTypes.MEDIA_TYPES;

	/**
	 * The table core.messages_queue
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.MessagesQueue MESSAGES_QUEUE = com.sonicle.webtop.core.jooq.core.tables.MessagesQueue.MESSAGES_QUEUE;

	/**
	 * The table core.roles
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Roles ROLES = com.sonicle.webtop.core.jooq.core.tables.Roles.ROLES;

	/**
	 * The table core.roles_associations
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.RolesAssociations ROLES_ASSOCIATIONS = com.sonicle.webtop.core.jooq.core.tables.RolesAssociations.ROLES_ASSOCIATIONS;

	/**
	 * The table core.roles_permissions
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.RolesPermissions ROLES_PERMISSIONS = com.sonicle.webtop.core.jooq.core.tables.RolesPermissions.ROLES_PERMISSIONS;

	/**
	 * The table core.servicestore_entries
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries SERVICESTORE_ENTRIES = com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES;

	/**
	 * The table core.settings
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Settings SETTINGS = com.sonicle.webtop.core.jooq.core.tables.Settings.SETTINGS;

	/**
	 * The table core.settings_db
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.SettingsDb SETTINGS_DB = com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB;

	/**
	 * The table core.shares
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Shares SHARES = com.sonicle.webtop.core.jooq.core.tables.Shares.SHARES;

	/**
	 * The table core.shares_data
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.SharesData SHARES_DATA = com.sonicle.webtop.core.jooq.core.tables.SharesData.SHARES_DATA;

	/**
	 * The table core.snoozed_reminders
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders SNOOZED_REMINDERS = com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS;

	/**
	 * The table core.syslog
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Syslog SYSLOG = com.sonicle.webtop.core.jooq.core.tables.Syslog.SYSLOG;

	/**
	 * The table core.upgrade_statements
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements UPGRADE_STATEMENTS = com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS;

	/**
	 * The table core.user_settings
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.UserSettings USER_SETTINGS = com.sonicle.webtop.core.jooq.core.tables.UserSettings.USER_SETTINGS;

	/**
	 * The table core.users
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.Users USERS = com.sonicle.webtop.core.jooq.core.tables.Users.USERS;

	/**
	 * The table core.users_associations
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.UsersAssociations USERS_ASSOCIATIONS = com.sonicle.webtop.core.jooq.core.tables.UsersAssociations.USERS_ASSOCIATIONS;

	/**
	 * The table core.users_info
	 */
	public static final com.sonicle.webtop.core.jooq.core.tables.UsersInfo USERS_INFO = com.sonicle.webtop.core.jooq.core.tables.UsersInfo.USERS_INFO;
}
