/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.config;

/**
 * Convenience access to all tables in config
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table config.fetchmail_polls
	 */
	public static final com.sonicle.webtop.core.jooq.config.tables.FetchmailPolls FETCHMAIL_POLLS = com.sonicle.webtop.core.jooq.config.tables.FetchmailPolls.FETCHMAIL_POLLS;

	/**
	 * The table config.pecbridge_fetchers
	 */
	public static final com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers PECBRIDGE_FETCHERS = com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS;

	/**
	 * The table config.pecbridge_relays
	 */
	public static final com.sonicle.webtop.core.jooq.config.tables.PecbridgeRelays PECBRIDGE_RELAYS = com.sonicle.webtop.core.jooq.config.tables.PecbridgeRelays.PECBRIDGE_RELAYS;

	/**
	 * The table config.virtual_aliases
	 */
	public static final com.sonicle.webtop.core.jooq.config.tables.VirtualAliases VIRTUAL_ALIASES = com.sonicle.webtop.core.jooq.config.tables.VirtualAliases.VIRTUAL_ALIASES;

	/**
	 * The table config.virtual_domain_names
	 */
	public static final com.sonicle.webtop.core.jooq.config.tables.VirtualDomainNames VIRTUAL_DOMAIN_NAMES = com.sonicle.webtop.core.jooq.config.tables.VirtualDomainNames.VIRTUAL_DOMAIN_NAMES;
}
