/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Causals implements java.io.Serializable {

	private static final long serialVersionUID = -1800841630;

	private java.lang.Integer causalId;
	private java.lang.String  domainId;
	private java.lang.String  userId;
	private java.lang.String  customerId;
	private java.lang.String  revisionStatus;
	private java.lang.String  description;
	private java.lang.Boolean readOnly;
	private java.lang.String  externalId;

	public Causals() {}

	public Causals(
		java.lang.Integer causalId,
		java.lang.String  domainId,
		java.lang.String  userId,
		java.lang.String  customerId,
		java.lang.String  revisionStatus,
		java.lang.String  description,
		java.lang.Boolean readOnly,
		java.lang.String  externalId
	) {
		this.causalId = causalId;
		this.domainId = domainId;
		this.userId = userId;
		this.customerId = customerId;
		this.revisionStatus = revisionStatus;
		this.description = description;
		this.readOnly = readOnly;
		this.externalId = externalId;
	}

	public java.lang.Integer getCausalId() {
		return this.causalId;
	}

	public void setCausalId(java.lang.Integer causalId) {
		this.causalId = causalId;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getRevisionStatus() {
		return this.revisionStatus;
	}

	public void setRevisionStatus(java.lang.String revisionStatus) {
		this.revisionStatus = revisionStatus;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Boolean getReadOnly() {
		return this.readOnly;
	}

	public void setReadOnly(java.lang.Boolean readOnly) {
		this.readOnly = readOnly;
	}

	public java.lang.String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(java.lang.String externalId) {
		this.externalId = externalId;
	}
}
