/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DomainSettings implements java.io.Serializable {

	private static final long serialVersionUID = -727748667;

	private java.lang.String domainId;
	private java.lang.String serviceId;
	private java.lang.String key;
	private java.lang.String value;

	public DomainSettings() {}

	public DomainSettings(
		java.lang.String domainId,
		java.lang.String serviceId,
		java.lang.String key,
		java.lang.String value
	) {
		this.domainId = domainId;
		this.serviceId = serviceId;
		this.key = key;
		this.value = value;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(java.lang.String serviceId) {
		this.serviceId = serviceId;
	}

	public java.lang.String getKey() {
		return this.key;
	}

	public void setKey(java.lang.String key) {
		this.key = key;
	}

	public java.lang.String getValue() {
		return this.value;
	}

	public void setValue(java.lang.String value) {
		this.value = value;
	}
}
