/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImChats implements java.io.Serializable {

	private static final long serialVersionUID = 167692711;

	private java.lang.Integer      id;
	private java.lang.String       domainId;
	private java.lang.String       userId;
	private java.lang.String       revisionStatus;
	private org.joda.time.DateTime revisionTimestamp;
	private java.lang.String       chatJid;
	private java.lang.String       ownerJid;
	private java.lang.String       name;
	private java.lang.Boolean      isGroupChat;
	private org.joda.time.DateTime lastSeenActivity;
	private java.lang.String       withJid;

	public ImChats() {}

	public ImChats(
		java.lang.Integer      id,
		java.lang.String       domainId,
		java.lang.String       userId,
		java.lang.String       revisionStatus,
		org.joda.time.DateTime revisionTimestamp,
		java.lang.String       chatJid,
		java.lang.String       ownerJid,
		java.lang.String       name,
		java.lang.Boolean      isGroupChat,
		org.joda.time.DateTime lastSeenActivity,
		java.lang.String       withJid
	) {
		this.id = id;
		this.domainId = domainId;
		this.userId = userId;
		this.revisionStatus = revisionStatus;
		this.revisionTimestamp = revisionTimestamp;
		this.chatJid = chatJid;
		this.ownerJid = ownerJid;
		this.name = name;
		this.isGroupChat = isGroupChat;
		this.lastSeenActivity = lastSeenActivity;
		this.withJid = withJid;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getRevisionStatus() {
		return this.revisionStatus;
	}

	public void setRevisionStatus(java.lang.String revisionStatus) {
		this.revisionStatus = revisionStatus;
	}

	public org.joda.time.DateTime getRevisionTimestamp() {
		return this.revisionTimestamp;
	}

	public void setRevisionTimestamp(org.joda.time.DateTime revisionTimestamp) {
		this.revisionTimestamp = revisionTimestamp;
	}

	public java.lang.String getChatJid() {
		return this.chatJid;
	}

	public void setChatJid(java.lang.String chatJid) {
		this.chatJid = chatJid;
	}

	public java.lang.String getOwnerJid() {
		return this.ownerJid;
	}

	public void setOwnerJid(java.lang.String ownerJid) {
		this.ownerJid = ownerJid;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Boolean getIsGroupChat() {
		return this.isGroupChat;
	}

	public void setIsGroupChat(java.lang.Boolean isGroupChat) {
		this.isGroupChat = isGroupChat;
	}

	public org.joda.time.DateTime getLastSeenActivity() {
		return this.lastSeenActivity;
	}

	public void setLastSeenActivity(org.joda.time.DateTime lastSeenActivity) {
		this.lastSeenActivity = lastSeenActivity;
	}

	public java.lang.String getWithJid() {
		return this.withJid;
	}

	public void setWithJid(java.lang.String withJid) {
		this.withJid = withJid;
	}
}
