/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImHistoryMessages implements java.io.Serializable {

	private static final long serialVersionUID = 805811194;

	private java.lang.Integer       id;
	private java.lang.String        domainId;
	private java.lang.String        userId;
	private java.lang.String        chatJid;
	private java.lang.String        senderJid;
	private java.lang.String        senderResource;
	private org.joda.time.LocalDate date;
	private org.joda.time.DateTime  timestamp;
	private java.lang.String        action;
	private java.lang.String        text;
	private java.lang.String        messageUid;
	private java.lang.String        stanzaId;

	public ImHistoryMessages() {}

	public ImHistoryMessages(
		java.lang.Integer       id,
		java.lang.String        domainId,
		java.lang.String        userId,
		java.lang.String        chatJid,
		java.lang.String        senderJid,
		java.lang.String        senderResource,
		org.joda.time.LocalDate date,
		org.joda.time.DateTime  timestamp,
		java.lang.String        action,
		java.lang.String        text,
		java.lang.String        messageUid,
		java.lang.String        stanzaId
	) {
		this.id = id;
		this.domainId = domainId;
		this.userId = userId;
		this.chatJid = chatJid;
		this.senderJid = senderJid;
		this.senderResource = senderResource;
		this.date = date;
		this.timestamp = timestamp;
		this.action = action;
		this.text = text;
		this.messageUid = messageUid;
		this.stanzaId = stanzaId;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getChatJid() {
		return this.chatJid;
	}

	public void setChatJid(java.lang.String chatJid) {
		this.chatJid = chatJid;
	}

	public java.lang.String getSenderJid() {
		return this.senderJid;
	}

	public void setSenderJid(java.lang.String senderJid) {
		this.senderJid = senderJid;
	}

	public java.lang.String getSenderResource() {
		return this.senderResource;
	}

	public void setSenderResource(java.lang.String senderResource) {
		this.senderResource = senderResource;
	}

	public org.joda.time.LocalDate getDate() {
		return this.date;
	}

	public void setDate(org.joda.time.LocalDate date) {
		this.date = date;
	}

	public org.joda.time.DateTime getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(org.joda.time.DateTime timestamp) {
		this.timestamp = timestamp;
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.String getText() {
		return this.text;
	}

	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getMessageUid() {
		return this.messageUid;
	}

	public void setMessageUid(java.lang.String messageUid) {
		this.messageUid = messageUid;
	}

	public java.lang.String getStanzaId() {
		return this.stanzaId;
	}

	public void setStanzaId(java.lang.String stanzaId) {
		this.stanzaId = stanzaId;
	}
}
