/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImMessages implements java.io.Serializable {

	private static final long serialVersionUID = 183166574;

	private java.lang.Integer      id;
	private java.lang.String       domainId;
	private java.lang.String       userId;
	private java.lang.String       chatJid;
	private java.lang.String       senderJid;
	private java.lang.String       senderResource;
	private org.joda.time.DateTime timestamp;
	private org.joda.time.DateTime deliveryTimestamp;
	private java.lang.String       action;
	private java.lang.String       text;
	private java.lang.String       messageUid;
	private java.lang.String       stanzaId;
	private java.lang.String       data;

	public ImMessages() {}

	public ImMessages(
		java.lang.Integer      id,
		java.lang.String       domainId,
		java.lang.String       userId,
		java.lang.String       chatJid,
		java.lang.String       senderJid,
		java.lang.String       senderResource,
		org.joda.time.DateTime timestamp,
		org.joda.time.DateTime deliveryTimestamp,
		java.lang.String       action,
		java.lang.String       text,
		java.lang.String       messageUid,
		java.lang.String       stanzaId,
		java.lang.String       data
	) {
		this.id = id;
		this.domainId = domainId;
		this.userId = userId;
		this.chatJid = chatJid;
		this.senderJid = senderJid;
		this.senderResource = senderResource;
		this.timestamp = timestamp;
		this.deliveryTimestamp = deliveryTimestamp;
		this.action = action;
		this.text = text;
		this.messageUid = messageUid;
		this.stanzaId = stanzaId;
		this.data = data;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getChatJid() {
		return this.chatJid;
	}

	public void setChatJid(java.lang.String chatJid) {
		this.chatJid = chatJid;
	}

	public java.lang.String getSenderJid() {
		return this.senderJid;
	}

	public void setSenderJid(java.lang.String senderJid) {
		this.senderJid = senderJid;
	}

	public java.lang.String getSenderResource() {
		return this.senderResource;
	}

	public void setSenderResource(java.lang.String senderResource) {
		this.senderResource = senderResource;
	}

	public org.joda.time.DateTime getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(org.joda.time.DateTime timestamp) {
		this.timestamp = timestamp;
	}

	public org.joda.time.DateTime getDeliveryTimestamp() {
		return this.deliveryTimestamp;
	}

	public void setDeliveryTimestamp(org.joda.time.DateTime deliveryTimestamp) {
		this.deliveryTimestamp = deliveryTimestamp;
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.String getText() {
		return this.text;
	}

	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getMessageUid() {
		return this.messageUid;
	}

	public void setMessageUid(java.lang.String messageUid) {
		this.messageUid = messageUid;
	}

	public java.lang.String getStanzaId() {
		return this.stanzaId;
	}

	public void setStanzaId(java.lang.String stanzaId) {
		this.stanzaId = stanzaId;
	}

	public java.lang.String getData() {
		return this.data;
	}

	public void setData(java.lang.String data) {
		this.data = data;
	}
}
