/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MasterData implements java.io.Serializable {

	private static final long serialVersionUID = -285279426;

	private java.lang.String       domainId;
	private java.lang.String       masterDataId;
	private java.lang.String       parentMasterDataId;
	private java.lang.String       externalId;
	private java.lang.String       type;
	private java.lang.String       revisionStatus;
	private org.joda.time.DateTime revisionTimestamp;
	private java.lang.Integer      revisionSequence;
	private java.lang.String       lockStatus;
	private java.lang.String       description;
	private java.lang.String       address;
	private java.lang.String       city;
	private java.lang.String       postalCode;
	private java.lang.String       state;
	private java.lang.String       country;
	private java.lang.String       telephone;
	private java.lang.String       fax;
	private java.lang.String       mobile;
	private java.lang.String       email;
	private java.lang.String       notes;
	private java.lang.Integer      distance;

	public MasterData() {}

	public MasterData(
		java.lang.String       domainId,
		java.lang.String       masterDataId,
		java.lang.String       parentMasterDataId,
		java.lang.String       externalId,
		java.lang.String       type,
		java.lang.String       revisionStatus,
		org.joda.time.DateTime revisionTimestamp,
		java.lang.Integer      revisionSequence,
		java.lang.String       lockStatus,
		java.lang.String       description,
		java.lang.String       address,
		java.lang.String       city,
		java.lang.String       postalCode,
		java.lang.String       state,
		java.lang.String       country,
		java.lang.String       telephone,
		java.lang.String       fax,
		java.lang.String       mobile,
		java.lang.String       email,
		java.lang.String       notes,
		java.lang.Integer      distance
	) {
		this.domainId = domainId;
		this.masterDataId = masterDataId;
		this.parentMasterDataId = parentMasterDataId;
		this.externalId = externalId;
		this.type = type;
		this.revisionStatus = revisionStatus;
		this.revisionTimestamp = revisionTimestamp;
		this.revisionSequence = revisionSequence;
		this.lockStatus = lockStatus;
		this.description = description;
		this.address = address;
		this.city = city;
		this.postalCode = postalCode;
		this.state = state;
		this.country = country;
		this.telephone = telephone;
		this.fax = fax;
		this.mobile = mobile;
		this.email = email;
		this.notes = notes;
		this.distance = distance;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getMasterDataId() {
		return this.masterDataId;
	}

	public void setMasterDataId(java.lang.String masterDataId) {
		this.masterDataId = masterDataId;
	}

	public java.lang.String getParentMasterDataId() {
		return this.parentMasterDataId;
	}

	public void setParentMasterDataId(java.lang.String parentMasterDataId) {
		this.parentMasterDataId = parentMasterDataId;
	}

	public java.lang.String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(java.lang.String externalId) {
		this.externalId = externalId;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getRevisionStatus() {
		return this.revisionStatus;
	}

	public void setRevisionStatus(java.lang.String revisionStatus) {
		this.revisionStatus = revisionStatus;
	}

	public org.joda.time.DateTime getRevisionTimestamp() {
		return this.revisionTimestamp;
	}

	public void setRevisionTimestamp(org.joda.time.DateTime revisionTimestamp) {
		this.revisionTimestamp = revisionTimestamp;
	}

	public java.lang.Integer getRevisionSequence() {
		return this.revisionSequence;
	}

	public void setRevisionSequence(java.lang.Integer revisionSequence) {
		this.revisionSequence = revisionSequence;
	}

	public java.lang.String getLockStatus() {
		return this.lockStatus;
	}

	public void setLockStatus(java.lang.String lockStatus) {
		this.lockStatus = lockStatus;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(java.lang.String postalCode) {
		this.postalCode = postalCode;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(java.lang.String telephone) {
		this.telephone = telephone;
	}

	public java.lang.String getFax() {
		return this.fax;
	}

	public void setFax(java.lang.String fax) {
		this.fax = fax;
	}

	public java.lang.String getMobile() {
		return this.mobile;
	}

	public void setMobile(java.lang.String mobile) {
		this.mobile = mobile;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getNotes() {
		return this.notes;
	}

	public void setNotes(java.lang.String notes) {
		this.notes = notes;
	}

	public java.lang.Integer getDistance() {
		return this.distance;
	}

	public void setDistance(java.lang.Integer distance) {
		this.distance = distance;
	}
}
