/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagesQueue implements java.io.Serializable {

	private static final long serialVersionUID = 1282013317;

	private java.lang.Integer      queueId;
	private java.lang.String       domainId;
	private java.lang.String       userId;
	private java.lang.String       messageType;
	private java.lang.String       messageRaw;
	private org.joda.time.DateTime queuedOn;
	private java.lang.String       pid;

	public MessagesQueue() {}

	public MessagesQueue(
		java.lang.Integer      queueId,
		java.lang.String       domainId,
		java.lang.String       userId,
		java.lang.String       messageType,
		java.lang.String       messageRaw,
		org.joda.time.DateTime queuedOn,
		java.lang.String       pid
	) {
		this.queueId = queueId;
		this.domainId = domainId;
		this.userId = userId;
		this.messageType = messageType;
		this.messageRaw = messageRaw;
		this.queuedOn = queuedOn;
		this.pid = pid;
	}

	public java.lang.Integer getQueueId() {
		return this.queueId;
	}

	public void setQueueId(java.lang.Integer queueId) {
		this.queueId = queueId;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(java.lang.String messageType) {
		this.messageType = messageType;
	}

	public java.lang.String getMessageRaw() {
		return this.messageRaw;
	}

	public void setMessageRaw(java.lang.String messageRaw) {
		this.messageRaw = messageRaw;
	}

	public org.joda.time.DateTime getQueuedOn() {
		return this.queuedOn;
	}

	public void setQueuedOn(org.joda.time.DateTime queuedOn) {
		this.queuedOn = queuedOn;
	}

	public java.lang.String getPid() {
		return this.pid;
	}

	public void setPid(java.lang.String pid) {
		this.pid = pid;
	}
}
