/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles implements java.io.Serializable {

	private static final long serialVersionUID = 1626671803;

	private java.lang.String roleUid;
	private java.lang.String domainId;
	private java.lang.String name;
	private java.lang.String description;

	public Roles() {}

	public Roles(
		java.lang.String roleUid,
		java.lang.String domainId,
		java.lang.String name,
		java.lang.String description
	) {
		this.roleUid = roleUid;
		this.domainId = domainId;
		this.name = name;
		this.description = description;
	}

	public java.lang.String getRoleUid() {
		return this.roleUid;
	}

	public void setRoleUid(java.lang.String roleUid) {
		this.roleUid = roleUid;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}
}
