/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesAssociations implements java.io.Serializable {

	private static final long serialVersionUID = -1180721857;

	private java.lang.Integer roleAssociationId;
	private java.lang.String  userUid;
	private java.lang.String  roleUid;

	public RolesAssociations() {}

	public RolesAssociations(
		java.lang.Integer roleAssociationId,
		java.lang.String  userUid,
		java.lang.String  roleUid
	) {
		this.roleAssociationId = roleAssociationId;
		this.userUid = userUid;
		this.roleUid = roleUid;
	}

	public java.lang.Integer getRoleAssociationId() {
		return this.roleAssociationId;
	}

	public void setRoleAssociationId(java.lang.Integer roleAssociationId) {
		this.roleAssociationId = roleAssociationId;
	}

	public java.lang.String getUserUid() {
		return this.userUid;
	}

	public void setUserUid(java.lang.String userUid) {
		this.userUid = userUid;
	}

	public java.lang.String getRoleUid() {
		return this.roleUid;
	}

	public void setRoleUid(java.lang.String roleUid) {
		this.roleUid = roleUid;
	}
}
