/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServicestoreEntries implements java.io.Serializable {

	private static final long serialVersionUID = -1241907984;

	private java.lang.String       domainId;
	private java.lang.String       userId;
	private java.lang.String       serviceId;
	private java.lang.String       context;
	private java.lang.String       key;
	private java.lang.String       value;
	private java.lang.Integer      frequency;
	private org.joda.time.DateTime lastUpdate;

	public ServicestoreEntries() {}

	public ServicestoreEntries(
		java.lang.String       domainId,
		java.lang.String       userId,
		java.lang.String       serviceId,
		java.lang.String       context,
		java.lang.String       key,
		java.lang.String       value,
		java.lang.Integer      frequency,
		org.joda.time.DateTime lastUpdate
	) {
		this.domainId = domainId;
		this.userId = userId;
		this.serviceId = serviceId;
		this.context = context;
		this.key = key;
		this.value = value;
		this.frequency = frequency;
		this.lastUpdate = lastUpdate;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(java.lang.String serviceId) {
		this.serviceId = serviceId;
	}

	public java.lang.String getContext() {
		return this.context;
	}

	public void setContext(java.lang.String context) {
		this.context = context;
	}

	public java.lang.String getKey() {
		return this.key;
	}

	public void setKey(java.lang.String key) {
		this.key = key;
	}

	public java.lang.String getValue() {
		return this.value;
	}

	public void setValue(java.lang.String value) {
		this.value = value;
	}

	public java.lang.Integer getFrequency() {
		return this.frequency;
	}

	public void setFrequency(java.lang.Integer frequency) {
		this.frequency = frequency;
	}

	public org.joda.time.DateTime getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(org.joda.time.DateTime lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
}
