/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsDb implements java.io.Serializable {

	private static final long serialVersionUID = -1372832133;

	private java.lang.String  serviceId;
	private java.lang.String  key;
	private java.lang.Boolean isSystem;
	private java.lang.Boolean isDomain;
	private java.lang.Boolean isUser;
	private java.lang.Boolean hidden;
	private java.lang.String  type;
	private java.lang.String  help;

	public SettingsDb() {}

	public SettingsDb(
		java.lang.String  serviceId,
		java.lang.String  key,
		java.lang.Boolean isSystem,
		java.lang.Boolean isDomain,
		java.lang.Boolean isUser,
		java.lang.Boolean hidden,
		java.lang.String  type,
		java.lang.String  help
	) {
		this.serviceId = serviceId;
		this.key = key;
		this.isSystem = isSystem;
		this.isDomain = isDomain;
		this.isUser = isUser;
		this.hidden = hidden;
		this.type = type;
		this.help = help;
	}

	public java.lang.String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(java.lang.String serviceId) {
		this.serviceId = serviceId;
	}

	public java.lang.String getKey() {
		return this.key;
	}

	public void setKey(java.lang.String key) {
		this.key = key;
	}

	public java.lang.Boolean getIsSystem() {
		return this.isSystem;
	}

	public void setIsSystem(java.lang.Boolean isSystem) {
		this.isSystem = isSystem;
	}

	public java.lang.Boolean getIsDomain() {
		return this.isDomain;
	}

	public void setIsDomain(java.lang.Boolean isDomain) {
		this.isDomain = isDomain;
	}

	public java.lang.Boolean getIsUser() {
		return this.isUser;
	}

	public void setIsUser(java.lang.Boolean isUser) {
		this.isUser = isUser;
	}

	public java.lang.Boolean getHidden() {
		return this.hidden;
	}

	public void setHidden(java.lang.Boolean hidden) {
		this.hidden = hidden;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getHelp() {
		return this.help;
	}

	public void setHelp(java.lang.String help) {
		this.help = help;
	}
}
