/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SharesData implements java.io.Serializable {

	private static final long serialVersionUID = -1801289598;

	private java.lang.Integer shareId;
	private java.lang.String  userUid;
	private java.lang.String  value;

	public SharesData() {}

	public SharesData(
		java.lang.Integer shareId,
		java.lang.String  userUid,
		java.lang.String  value
	) {
		this.shareId = shareId;
		this.userUid = userUid;
		this.value = value;
	}

	public java.lang.Integer getShareId() {
		return this.shareId;
	}

	public void setShareId(java.lang.Integer shareId) {
		this.shareId = shareId;
	}

	public java.lang.String getUserUid() {
		return this.userUid;
	}

	public void setUserUid(java.lang.String userUid) {
		this.userUid = userUid;
	}

	public java.lang.String getValue() {
		return this.value;
	}

	public void setValue(java.lang.String value) {
		this.value = value;
	}
}
