/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SnoozedReminders implements java.io.Serializable {

	private static final long serialVersionUID = 786304097;

	private java.lang.Integer      snoozedReminderId;
	private java.lang.String       domainId;
	private java.lang.String       userId;
	private java.lang.String       serviceId;
	private java.lang.String       type;
	private java.lang.String       instanceId;
	private org.joda.time.DateTime remindOn;
	private java.lang.String       title;
	private org.joda.time.DateTime date;
	private java.lang.String       timezone;

	public SnoozedReminders() {}

	public SnoozedReminders(
		java.lang.Integer      snoozedReminderId,
		java.lang.String       domainId,
		java.lang.String       userId,
		java.lang.String       serviceId,
		java.lang.String       type,
		java.lang.String       instanceId,
		org.joda.time.DateTime remindOn,
		java.lang.String       title,
		org.joda.time.DateTime date,
		java.lang.String       timezone
	) {
		this.snoozedReminderId = snoozedReminderId;
		this.domainId = domainId;
		this.userId = userId;
		this.serviceId = serviceId;
		this.type = type;
		this.instanceId = instanceId;
		this.remindOn = remindOn;
		this.title = title;
		this.date = date;
		this.timezone = timezone;
	}

	public java.lang.Integer getSnoozedReminderId() {
		return this.snoozedReminderId;
	}

	public void setSnoozedReminderId(java.lang.Integer snoozedReminderId) {
		this.snoozedReminderId = snoozedReminderId;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(java.lang.String serviceId) {
		this.serviceId = serviceId;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(java.lang.String instanceId) {
		this.instanceId = instanceId;
	}

	public org.joda.time.DateTime getRemindOn() {
		return this.remindOn;
	}

	public void setRemindOn(org.joda.time.DateTime remindOn) {
		this.remindOn = remindOn;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public org.joda.time.DateTime getDate() {
		return this.date;
	}

	public void setDate(org.joda.time.DateTime date) {
		this.date = date;
	}

	public java.lang.String getTimezone() {
		return this.timezone;
	}

	public void setTimezone(java.lang.String timezone) {
		this.timezone = timezone;
	}
}
