/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpgradeStatements implements java.io.Serializable {

	private static final long serialVersionUID = 1789025736;

	private java.lang.Integer      upgradeStatementId;
	private java.lang.String       tag;
	private java.lang.String       serviceId;
	private java.lang.Short        sequenceNo;
	private java.lang.String       scriptName;
	private java.lang.String       statementType;
	private java.lang.String       statementDataSource;
	private java.lang.String       statementBody;
	private java.lang.String       runStatus;
	private org.joda.time.DateTime runTimestamp;
	private java.lang.String       runMessage;

	public UpgradeStatements() {}

	public UpgradeStatements(
		java.lang.Integer      upgradeStatementId,
		java.lang.String       tag,
		java.lang.String       serviceId,
		java.lang.Short        sequenceNo,
		java.lang.String       scriptName,
		java.lang.String       statementType,
		java.lang.String       statementDataSource,
		java.lang.String       statementBody,
		java.lang.String       runStatus,
		org.joda.time.DateTime runTimestamp,
		java.lang.String       runMessage
	) {
		this.upgradeStatementId = upgradeStatementId;
		this.tag = tag;
		this.serviceId = serviceId;
		this.sequenceNo = sequenceNo;
		this.scriptName = scriptName;
		this.statementType = statementType;
		this.statementDataSource = statementDataSource;
		this.statementBody = statementBody;
		this.runStatus = runStatus;
		this.runTimestamp = runTimestamp;
		this.runMessage = runMessage;
	}

	public java.lang.Integer getUpgradeStatementId() {
		return this.upgradeStatementId;
	}

	public void setUpgradeStatementId(java.lang.Integer upgradeStatementId) {
		this.upgradeStatementId = upgradeStatementId;
	}

	public java.lang.String getTag() {
		return this.tag;
	}

	public void setTag(java.lang.String tag) {
		this.tag = tag;
	}

	public java.lang.String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(java.lang.String serviceId) {
		this.serviceId = serviceId;
	}

	public java.lang.Short getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(java.lang.Short sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	public java.lang.String getScriptName() {
		return this.scriptName;
	}

	public void setScriptName(java.lang.String scriptName) {
		this.scriptName = scriptName;
	}

	public java.lang.String getStatementType() {
		return this.statementType;
	}

	public void setStatementType(java.lang.String statementType) {
		this.statementType = statementType;
	}

	public java.lang.String getStatementDataSource() {
		return this.statementDataSource;
	}

	public void setStatementDataSource(java.lang.String statementDataSource) {
		this.statementDataSource = statementDataSource;
	}

	public java.lang.String getStatementBody() {
		return this.statementBody;
	}

	public void setStatementBody(java.lang.String statementBody) {
		this.statementBody = statementBody;
	}

	public java.lang.String getRunStatus() {
		return this.runStatus;
	}

	public void setRunStatus(java.lang.String runStatus) {
		this.runStatus = runStatus;
	}

	public org.joda.time.DateTime getRunTimestamp() {
		return this.runTimestamp;
	}

	public void setRunTimestamp(org.joda.time.DateTime runTimestamp) {
		this.runTimestamp = runTimestamp;
	}

	public java.lang.String getRunMessage() {
		return this.runMessage;
	}

	public void setRunMessage(java.lang.String runMessage) {
		this.runMessage = runMessage;
	}
}
