/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.config.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VirtualAliases implements java.io.Serializable {

	private static final long serialVersionUID = -1567729882;

	private java.lang.Integer virtualAliasId;
	private java.lang.String  context;
	private java.lang.String  name;
	private java.lang.String  address;

	public VirtualAliases() {}

	public VirtualAliases(
		java.lang.Integer virtualAliasId,
		java.lang.String  context,
		java.lang.String  name,
		java.lang.String  address
	) {
		this.virtualAliasId = virtualAliasId;
		this.context = context;
		this.name = name;
		this.address = address;
	}

	public java.lang.Integer getVirtualAliasId() {
		return this.virtualAliasId;
	}

	public void setVirtualAliasId(java.lang.Integer virtualAliasId) {
		this.virtualAliasId = virtualAliasId;
	}

	public java.lang.String getContext() {
		return this.context;
	}

	public void setContext(java.lang.String context) {
		this.context = context;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}
}
