/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ____CustomersRecord extends org.jooq.impl.TableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.____CustomersRecord> implements org.jooq.Record18<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1288371942;

	/**
	 * Setter for <code>core.____customers.customer_id</code>.
	 */
	public void setCustomerId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.____customers.customer_id</code>.
	 */
	public java.lang.String getCustomerId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>core.____customers.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.____customers.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.____customers.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.____customers.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>core.____customers.address</code>.
	 */
	public void setAddress(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>core.____customers.address</code>.
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>core.____customers.city</code>.
	 */
	public void setCity(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>core.____customers.city</code>.
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>core.____customers.state</code>.
	 */
	public void setState(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>core.____customers.state</code>.
	 */
	public java.lang.String getState() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>core.____customers.postalcode</code>.
	 */
	public void setPostalcode(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>core.____customers.postalcode</code>.
	 */
	public java.lang.String getPostalcode() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>core.____customers.country</code>.
	 */
	public void setCountry(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>core.____customers.country</code>.
	 */
	public java.lang.String getCountry() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>core.____customers.telephone</code>.
	 */
	public void setTelephone(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>core.____customers.telephone</code>.
	 */
	public java.lang.String getTelephone() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>core.____customers.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>core.____customers.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>core.____customers.from_drm</code>.
	 */
	public void setFromDrm(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>core.____customers.from_drm</code>.
	 */
	public java.lang.String getFromDrm() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>core.____customers.parent_id</code>.
	 */
	public void setParentId(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>core.____customers.parent_id</code>.
	 */
	public java.lang.String getParentId() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>core.____customers.external_id</code>.
	 */
	public void setExternalId(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>core.____customers.external_id</code>.
	 */
	public java.lang.String getExternalId() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>core.____customers.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>core.____customers.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>core.____customers.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>core.____customers.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>core.____customers.km</code>.
	 */
	public void setKm(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>core.____customers.km</code>.
	 */
	public java.lang.String getKm() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>core.____customers.lock</code>.
	 */
	public void setLock(java.lang.String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>core.____customers.lock</code>.
	 */
	public java.lang.String getLock() {
		return (java.lang.String) getValue(16);
	}

	/**
	 * Setter for <code>core.____customers.note</code>.
	 */
	public void setNote(java.lang.String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>core.____customers.note</code>.
	 */
	public java.lang.String getNote() {
		return (java.lang.String) getValue(17);
	}

	// -------------------------------------------------------------------------
	// Record18 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row18<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row18) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row18<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row18) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.CUSTOMER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.POSTALCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.TELEPHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.FROM_DRM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.PARENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.EXTERNAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.KM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field17() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.LOCK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field18() {
		return com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS.NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getCustomerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getPostalcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getTelephone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getFromDrm();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getParentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getExternalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getKm();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value17() {
		return getLock();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value18() {
		return getNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value1(java.lang.String value) {
		setCustomerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value2(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value3(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value4(java.lang.String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value5(java.lang.String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value6(java.lang.String value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value7(java.lang.String value) {
		setPostalcode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value8(java.lang.String value) {
		setCountry(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value9(java.lang.String value) {
		setTelephone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value10(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value11(java.lang.String value) {
		setFromDrm(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value12(java.lang.String value) {
		setParentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value13(java.lang.String value) {
		setExternalId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value14(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value15(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value16(java.lang.String value) {
		setKm(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value17(java.lang.String value) {
		setLock(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord value18(java.lang.String value) {
		setNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ____CustomersRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.String value11, java.lang.String value12, java.lang.String value13, java.lang.String value14, java.lang.String value15, java.lang.String value16, java.lang.String value17, java.lang.String value18) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ____CustomersRecord
	 */
	public ____CustomersRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS);
	}

	/**
	 * Create a detached, initialised ____CustomersRecord
	 */
	public ____CustomersRecord(java.lang.String customerId, java.lang.String description, java.lang.String type, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String postalcode, java.lang.String country, java.lang.String telephone, java.lang.String email, java.lang.String fromDrm, java.lang.String parentId, java.lang.String externalId, java.lang.String status, java.lang.String domainId, java.lang.String km, java.lang.String lock, java.lang.String note) {
		super(com.sonicle.webtop.core.jooq.core.tables.____Customers.____CUSTOMERS);

		setValue(0, customerId);
		setValue(1, description);
		setValue(2, type);
		setValue(3, address);
		setValue(4, city);
		setValue(5, state);
		setValue(6, postalcode);
		setValue(7, country);
		setValue(8, telephone);
		setValue(9, email);
		setValue(10, fromDrm);
		setValue(11, parentId);
		setValue(12, externalId);
		setValue(13, status);
		setValue(14, domainId);
		setValue(15, km);
		setValue(16, lock);
		setValue(17, note);
	}
}
