/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivitiesRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.ActivitiesRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String> {

	private static final long serialVersionUID = -935057526;

	/**
	 * Setter for <code>core.activities.activity_id</code>.
	 */
	public void setActivityId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.activities.activity_id</code>.
	 */
	public java.lang.Integer getActivityId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>core.activities.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.activities.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.activities.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.activities.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>core.activities.revision_status</code>.
	 */
	public void setRevisionStatus(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>core.activities.revision_status</code>.
	 */
	public java.lang.String getRevisionStatus() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>core.activities.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>core.activities.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>core.activities.read_only</code>.
	 */
	public void setReadOnly(java.lang.Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>core.activities.read_only</code>.
	 */
	public java.lang.Boolean getReadOnly() {
		return (java.lang.Boolean) getValue(5);
	}

	/**
	 * Setter for <code>core.activities.external_id</code>.
	 */
	public void setExternalId(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>core.activities.external_id</code>.
	 */
	public java.lang.String getExternalId() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.Activities.ACTIVITIES.ACTIVITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.Activities.ACTIVITIES.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.Activities.ACTIVITIES.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.core.jooq.core.tables.Activities.ACTIVITIES.REVISION_STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.core.jooq.core.tables.Activities.ACTIVITIES.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field6() {
		return com.sonicle.webtop.core.jooq.core.tables.Activities.ACTIVITIES.READ_ONLY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.core.jooq.core.tables.Activities.ACTIVITIES.EXTERNAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getActivityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getRevisionStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value6() {
		return getReadOnly();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getExternalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitiesRecord value1(java.lang.Integer value) {
		setActivityId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitiesRecord value2(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitiesRecord value3(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitiesRecord value4(java.lang.String value) {
		setRevisionStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitiesRecord value5(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitiesRecord value6(java.lang.Boolean value) {
		setReadOnly(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitiesRecord value7(java.lang.String value) {
		setExternalId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitiesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.Boolean value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActivitiesRecord
	 */
	public ActivitiesRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.Activities.ACTIVITIES);
	}

	/**
	 * Create a detached, initialised ActivitiesRecord
	 */
	public ActivitiesRecord(java.lang.Integer activityId, java.lang.String domainId, java.lang.String userId, java.lang.String revisionStatus, java.lang.String description, java.lang.Boolean readOnly, java.lang.String externalId) {
		super(com.sonicle.webtop.core.jooq.core.tables.Activities.ACTIVITIES);

		setValue(0, activityId);
		setValue(1, domainId);
		setValue(2, userId);
		setValue(3, revisionStatus);
		setValue(4, description);
		setValue(5, readOnly);
		setValue(6, externalId);
	}
}
