/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutosaveRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.AutosaveRecord> implements org.jooq.Record7<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 439326040;

	/**
	 * Setter for <code>core.autosave.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.autosave.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>core.autosave.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.autosave.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.autosave.webtop_client_id</code>.
	 */
	public void setWebtopClientId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.autosave.webtop_client_id</code>.
	 */
	public java.lang.String getWebtopClientId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>core.autosave.service_id</code>.
	 */
	public void setServiceId(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>core.autosave.service_id</code>.
	 */
	public java.lang.String getServiceId() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>core.autosave.context</code>.
	 */
	public void setContext(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>core.autosave.context</code>.
	 */
	public java.lang.String getContext() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>core.autosave.key</code>.
	 */
	public void setKey(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>core.autosave.key</code>.
	 */
	public java.lang.String getKey() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>core.autosave.value</code>.
	 */
	public void setValue(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>core.autosave.value</code>.
	 */
	public java.lang.String getValue() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record6<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> key() {
		return (org.jooq.Record6) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.Autosave.AUTOSAVE.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.Autosave.AUTOSAVE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.Autosave.AUTOSAVE.WEBTOP_CLIENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.core.jooq.core.tables.Autosave.AUTOSAVE.SERVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.core.jooq.core.tables.Autosave.AUTOSAVE.CONTEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.core.jooq.core.tables.Autosave.AUTOSAVE.KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.core.jooq.core.tables.Autosave.AUTOSAVE.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getWebtopClientId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getServiceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getContext();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutosaveRecord value1(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutosaveRecord value2(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutosaveRecord value3(java.lang.String value) {
		setWebtopClientId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutosaveRecord value4(java.lang.String value) {
		setServiceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutosaveRecord value5(java.lang.String value) {
		setContext(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutosaveRecord value6(java.lang.String value) {
		setKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutosaveRecord value7(java.lang.String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutosaveRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AutosaveRecord
	 */
	public AutosaveRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.Autosave.AUTOSAVE);
	}

	/**
	 * Create a detached, initialised AutosaveRecord
	 */
	public AutosaveRecord(java.lang.String domainId, java.lang.String userId, java.lang.String webtopClientId, java.lang.String serviceId, java.lang.String context, java.lang.String key, java.lang.String value) {
		super(com.sonicle.webtop.core.jooq.core.tables.Autosave.AUTOSAVE);

		setValue(0, domainId);
		setValue(1, userId);
		setValue(2, webtopClientId);
		setValue(3, serviceId);
		setValue(4, context);
		setValue(5, key);
		setValue(6, value);
	}
}
