/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DomainsRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.DomainsRecord> implements org.jooq.Record12<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.String> {

	private static final long serialVersionUID = -1447385390;

	/**
	 * Setter for <code>core.domains.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.domains.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>core.domains.internet_name</code>.
	 */
	public void setInternetName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.domains.internet_name</code>.
	 */
	public java.lang.String getInternetName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.domains.enabled</code>.
	 */
	public void setEnabled(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.domains.enabled</code>.
	 */
	public java.lang.Boolean getEnabled() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>core.domains.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>core.domains.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>core.domains.user_auto_creation</code>.
	 */
	public void setUserAutoCreation(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>core.domains.user_auto_creation</code>.
	 */
	public java.lang.Boolean getUserAutoCreation() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>core.domains.dir_uri</code>.
	 */
	public void setDirUri(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>core.domains.dir_uri</code>.
	 */
	public java.lang.String getDirUri() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>core.domains.dir_admin</code>.
	 */
	public void setDirAdmin(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>core.domains.dir_admin</code>.
	 */
	public java.lang.String getDirAdmin() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>core.domains.dir_password</code>.
	 */
	public void setDirPassword(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>core.domains.dir_password</code>.
	 */
	public java.lang.String getDirPassword() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>core.domains.dir_connection_security</code>.
	 */
	public void setDirConnectionSecurity(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>core.domains.dir_connection_security</code>.
	 */
	public java.lang.String getDirConnectionSecurity() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>core.domains.dir_case_sensitive</code>.
	 */
	public void setDirCaseSensitive(java.lang.Boolean value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>core.domains.dir_case_sensitive</code>.
	 */
	public java.lang.Boolean getDirCaseSensitive() {
		return (java.lang.Boolean) getValue(9);
	}

	/**
	 * Setter for <code>core.domains.dir_password_policy</code>.
	 */
	public void setDirPasswordPolicy(java.lang.Boolean value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>core.domains.dir_password_policy</code>.
	 */
	public java.lang.Boolean getDirPasswordPolicy() {
		return (java.lang.Boolean) getValue(10);
	}

	/**
	 * Setter for <code>core.domains.dir_parameters</code>.
	 */
	public void setDirParameters(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>core.domains.dir_parameters</code>.
	 */
	public java.lang.String getDirParameters() {
		return (java.lang.String) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.String> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.String> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.INTERNET_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.USER_AUTO_CREATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.DIR_URI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.DIR_ADMIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.DIR_PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.DIR_CONNECTION_SECURITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field10() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.DIR_CASE_SENSITIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field11() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.DIR_PASSWORD_POLICY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS.DIR_PARAMETERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getInternetName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getUserAutoCreation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getDirUri();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getDirAdmin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getDirPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getDirConnectionSecurity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value10() {
		return getDirCaseSensitive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value11() {
		return getDirPasswordPolicy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getDirParameters();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value1(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value2(java.lang.String value) {
		setInternetName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value3(java.lang.Boolean value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value4(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value5(java.lang.Boolean value) {
		setUserAutoCreation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value6(java.lang.String value) {
		setDirUri(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value7(java.lang.String value) {
		setDirAdmin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value8(java.lang.String value) {
		setDirPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value9(java.lang.String value) {
		setDirConnectionSecurity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value10(java.lang.Boolean value) {
		setDirCaseSensitive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value11(java.lang.Boolean value) {
		setDirPasswordPolicy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord value12(java.lang.String value) {
		setDirParameters(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainsRecord values(java.lang.String value1, java.lang.String value2, java.lang.Boolean value3, java.lang.String value4, java.lang.Boolean value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.Boolean value10, java.lang.Boolean value11, java.lang.String value12) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DomainsRecord
	 */
	public DomainsRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS);
	}

	/**
	 * Create a detached, initialised DomainsRecord
	 */
	public DomainsRecord(java.lang.String domainId, java.lang.String internetName, java.lang.Boolean enabled, java.lang.String description, java.lang.Boolean userAutoCreation, java.lang.String dirUri, java.lang.String dirAdmin, java.lang.String dirPassword, java.lang.String dirConnectionSecurity, java.lang.Boolean dirCaseSensitive, java.lang.Boolean dirPasswordPolicy, java.lang.String dirParameters) {
		super(com.sonicle.webtop.core.jooq.core.tables.Domains.DOMAINS);

		setValue(0, domainId);
		setValue(1, internetName);
		setValue(2, enabled);
		setValue(3, description);
		setValue(4, userAutoCreation);
		setValue(5, dirUri);
		setValue(6, dirAdmin);
		setValue(7, dirPassword);
		setValue(8, dirConnectionSecurity);
		setValue(9, dirCaseSensitive);
		setValue(10, dirPasswordPolicy);
		setValue(11, dirParameters);
	}
}
