/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileTypesRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.FileTypesRecord> implements org.jooq.Record3<java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -82591929;

	/**
	 * Setter for <code>core.file_types.extension</code>.
	 */
	public void setExtension(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.file_types.extension</code>.
	 */
	public java.lang.String getExtension() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>core.file_types.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.file_types.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.file_types.subtype</code>.
	 */
	public void setSubtype(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.file_types.subtype</code>.
	 */
	public java.lang.String getSubtype() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.lang.String, java.lang.String, java.lang.String> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.FileTypes.FILE_TYPES.EXTENSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.FileTypes.FILE_TYPES.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.FileTypes.FILE_TYPES.SUBTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getExtension();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSubtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileTypesRecord value1(java.lang.String value) {
		setExtension(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileTypesRecord value2(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileTypesRecord value3(java.lang.String value) {
		setSubtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileTypesRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FileTypesRecord
	 */
	public FileTypesRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.FileTypes.FILE_TYPES);
	}

	/**
	 * Create a detached, initialised FileTypesRecord
	 */
	public FileTypesRecord(java.lang.String extension, java.lang.String type, java.lang.String subtype) {
		super(com.sonicle.webtop.core.jooq.core.tables.FileTypes.FILE_TYPES);

		setValue(0, extension);
		setValue(1, type);
		setValue(2, subtype);
	}
}
