/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MediaTypesRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.MediaTypesRecord> implements org.jooq.Record2<java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1709841507;

	/**
	 * Setter for <code>core.media_types.extension</code>.
	 */
	public void setExtension(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.media_types.extension</code>.
	 */
	public java.lang.String getExtension() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>core.media_types.media_type</code>.
	 */
	public void setMediaType(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.media_types.media_type</code>.
	 */
	public java.lang.String getMediaType() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.MediaTypes.MEDIA_TYPES.EXTENSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.MediaTypes.MEDIA_TYPES.MEDIA_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getExtension();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getMediaType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MediaTypesRecord value1(java.lang.String value) {
		setExtension(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MediaTypesRecord value2(java.lang.String value) {
		setMediaType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MediaTypesRecord values(java.lang.String value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MediaTypesRecord
	 */
	public MediaTypesRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.MediaTypes.MEDIA_TYPES);
	}

	/**
	 * Create a detached, initialised MediaTypesRecord
	 */
	public MediaTypesRecord(java.lang.String extension, java.lang.String mediaType) {
		super(com.sonicle.webtop.core.jooq.core.tables.MediaTypes.MEDIA_TYPES);

		setValue(0, extension);
		setValue(1, mediaType);
	}
}
