/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagesQueueRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.MessagesQueueRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String> {

	private static final long serialVersionUID = -402790979;

	/**
	 * Setter for <code>core.messages_queue.queue_id</code>.
	 */
	public void setQueueId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.messages_queue.queue_id</code>.
	 */
	public java.lang.Integer getQueueId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>core.messages_queue.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.messages_queue.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.messages_queue.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.messages_queue.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>core.messages_queue.message_type</code>.
	 */
	public void setMessageType(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>core.messages_queue.message_type</code>.
	 */
	public java.lang.String getMessageType() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>core.messages_queue.message_raw</code>.
	 */
	public void setMessageRaw(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>core.messages_queue.message_raw</code>.
	 */
	public java.lang.String getMessageRaw() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>core.messages_queue.queued_on</code>.
	 */
	public void setQueuedOn(org.joda.time.DateTime value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>core.messages_queue.queued_on</code>.
	 */
	public org.joda.time.DateTime getQueuedOn() {
		return (org.joda.time.DateTime) getValue(5);
	}

	/**
	 * Setter for <code>core.messages_queue.pid</code>.
	 */
	public void setPid(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>core.messages_queue.pid</code>.
	 */
	public java.lang.String getPid() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.MessagesQueue.MESSAGES_QUEUE.QUEUE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.MessagesQueue.MESSAGES_QUEUE.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.MessagesQueue.MESSAGES_QUEUE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.core.jooq.core.tables.MessagesQueue.MESSAGES_QUEUE.MESSAGE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.core.jooq.core.tables.MessagesQueue.MESSAGES_QUEUE.MESSAGE_RAW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field6() {
		return com.sonicle.webtop.core.jooq.core.tables.MessagesQueue.MESSAGES_QUEUE.QUEUED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.core.jooq.core.tables.MessagesQueue.MESSAGES_QUEUE.PID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getQueueId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getMessageType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getMessageRaw();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value6() {
		return getQueuedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getPid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesQueueRecord value1(java.lang.Integer value) {
		setQueueId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesQueueRecord value2(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesQueueRecord value3(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesQueueRecord value4(java.lang.String value) {
		setMessageType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesQueueRecord value5(java.lang.String value) {
		setMessageRaw(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesQueueRecord value6(org.joda.time.DateTime value) {
		setQueuedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesQueueRecord value7(java.lang.String value) {
		setPid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesQueueRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, org.joda.time.DateTime value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MessagesQueueRecord
	 */
	public MessagesQueueRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.MessagesQueue.MESSAGES_QUEUE);
	}

	/**
	 * Create a detached, initialised MessagesQueueRecord
	 */
	public MessagesQueueRecord(java.lang.Integer queueId, java.lang.String domainId, java.lang.String userId, java.lang.String messageType, java.lang.String messageRaw, org.joda.time.DateTime queuedOn, java.lang.String pid) {
		super(com.sonicle.webtop.core.jooq.core.tables.MessagesQueue.MESSAGES_QUEUE);

		setValue(0, queueId);
		setValue(1, domainId);
		setValue(2, userId);
		setValue(3, messageType);
		setValue(4, messageRaw);
		setValue(5, queuedOn);
		setValue(6, pid);
	}
}
