/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesPermissionsRecord extends org.jooq.impl.TableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.RolesPermissionsRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1331143237;

	/**
	 * Setter for <code>core.roles_permissions.role_permission_id</code>.
	 */
	public void setRolePermissionId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.roles_permissions.role_permission_id</code>.
	 */
	public java.lang.Integer getRolePermissionId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>core.roles_permissions.role_uid</code>.
	 */
	public void setRoleUid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.roles_permissions.role_uid</code>.
	 */
	public java.lang.String getRoleUid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.roles_permissions.service_id</code>.
	 */
	public void setServiceId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.roles_permissions.service_id</code>.
	 */
	public java.lang.String getServiceId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>core.roles_permissions.key</code>.
	 */
	public void setKey(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>core.roles_permissions.key</code>.
	 */
	public java.lang.String getKey() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>core.roles_permissions.action</code>.
	 */
	public void setAction(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>core.roles_permissions.action</code>.
	 */
	public java.lang.String getAction() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>core.roles_permissions.instance</code>.
	 */
	public void setInstance(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>core.roles_permissions.instance</code>.
	 */
	public java.lang.String getInstance() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.RolesPermissions.ROLES_PERMISSIONS.ROLE_PERMISSION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.RolesPermissions.ROLES_PERMISSIONS.ROLE_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.RolesPermissions.ROLES_PERMISSIONS.SERVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.core.jooq.core.tables.RolesPermissions.ROLES_PERMISSIONS.KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.core.jooq.core.tables.RolesPermissions.ROLES_PERMISSIONS.ACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.core.jooq.core.tables.RolesPermissions.ROLES_PERMISSIONS.INSTANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getRolePermissionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getRoleUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getServiceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getAction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getInstance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolesPermissionsRecord value1(java.lang.Integer value) {
		setRolePermissionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolesPermissionsRecord value2(java.lang.String value) {
		setRoleUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolesPermissionsRecord value3(java.lang.String value) {
		setServiceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolesPermissionsRecord value4(java.lang.String value) {
		setKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolesPermissionsRecord value5(java.lang.String value) {
		setAction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolesPermissionsRecord value6(java.lang.String value) {
		setInstance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolesPermissionsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RolesPermissionsRecord
	 */
	public RolesPermissionsRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.RolesPermissions.ROLES_PERMISSIONS);
	}

	/**
	 * Create a detached, initialised RolesPermissionsRecord
	 */
	public RolesPermissionsRecord(java.lang.Integer rolePermissionId, java.lang.String roleUid, java.lang.String serviceId, java.lang.String key, java.lang.String action, java.lang.String instance) {
		super(com.sonicle.webtop.core.jooq.core.tables.RolesPermissions.ROLES_PERMISSIONS);

		setValue(0, rolePermissionId);
		setValue(1, roleUid);
		setValue(2, serviceId);
		setValue(3, key);
		setValue(4, action);
		setValue(5, instance);
	}
}
