/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesAssociationsRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.RolesAssociationsRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 777146519;

	/**
	 * Setter for <code>core.roles_associations.role_association_id</code>.
	 */
	public void setRoleAssociationId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.roles_associations.role_association_id</code>.
	 */
	public java.lang.Integer getRoleAssociationId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>core.roles_associations.user_uid</code>.
	 */
	public void setUserUid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.roles_associations.user_uid</code>.
	 */
	public java.lang.String getUserUid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.roles_associations.role_uid</code>.
	 */
	public void setRoleUid(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.roles_associations.role_uid</code>.
	 */
	public java.lang.String getRoleUid() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.RolesAssociations.ROLES_ASSOCIATIONS.ROLE_ASSOCIATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.RolesAssociations.ROLES_ASSOCIATIONS.USER_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.RolesAssociations.ROLES_ASSOCIATIONS.ROLE_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getRoleAssociationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUserUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getRoleUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolesAssociationsRecord value1(java.lang.Integer value) {
		setRoleAssociationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolesAssociationsRecord value2(java.lang.String value) {
		setUserUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolesAssociationsRecord value3(java.lang.String value) {
		setRoleUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolesAssociationsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RolesAssociationsRecord
	 */
	public RolesAssociationsRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.RolesAssociations.ROLES_ASSOCIATIONS);
	}

	/**
	 * Create a detached, initialised RolesAssociationsRecord
	 */
	public RolesAssociationsRecord(java.lang.Integer roleAssociationId, java.lang.String userUid, java.lang.String roleUid) {
		super(com.sonicle.webtop.core.jooq.core.tables.RolesAssociations.ROLES_ASSOCIATIONS);

		setValue(0, roleAssociationId);
		setValue(1, userUid);
		setValue(2, roleUid);
	}
}
