/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServicestoreEntriesRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.ServicestoreEntriesRecord> implements org.jooq.Record8<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, org.joda.time.DateTime> {

	private static final long serialVersionUID = 640396635;

	/**
	 * Setter for <code>core.servicestore_entries.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.servicestore_entries.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>core.servicestore_entries.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.servicestore_entries.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.servicestore_entries.service_id</code>.
	 */
	public void setServiceId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.servicestore_entries.service_id</code>.
	 */
	public java.lang.String getServiceId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>core.servicestore_entries.context</code>.
	 */
	public void setContext(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>core.servicestore_entries.context</code>.
	 */
	public java.lang.String getContext() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>core.servicestore_entries.key</code>.
	 */
	public void setKey(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>core.servicestore_entries.key</code>.
	 */
	public java.lang.String getKey() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>core.servicestore_entries.value</code>.
	 */
	public void setValue(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>core.servicestore_entries.value</code>.
	 */
	public java.lang.String getValue() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>core.servicestore_entries.frequency</code>.
	 */
	public void setFrequency(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>core.servicestore_entries.frequency</code>.
	 */
	public java.lang.Integer getFrequency() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>core.servicestore_entries.last_update</code>.
	 */
	public void setLastUpdate(org.joda.time.DateTime value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>core.servicestore_entries.last_update</code>.
	 */
	public org.joda.time.DateTime getLastUpdate() {
		return (org.joda.time.DateTime) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record5<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> key() {
		return (org.jooq.Record5) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, org.joda.time.DateTime> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, org.joda.time.DateTime> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES.SERVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES.CONTEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES.KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES.FREQUENCY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field8() {
		return com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES.LAST_UPDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getServiceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getContext();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getFrequency();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value8() {
		return getLastUpdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ServicestoreEntriesRecord value1(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ServicestoreEntriesRecord value2(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ServicestoreEntriesRecord value3(java.lang.String value) {
		setServiceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ServicestoreEntriesRecord value4(java.lang.String value) {
		setContext(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ServicestoreEntriesRecord value5(java.lang.String value) {
		setKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ServicestoreEntriesRecord value6(java.lang.String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ServicestoreEntriesRecord value7(java.lang.Integer value) {
		setFrequency(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ServicestoreEntriesRecord value8(org.joda.time.DateTime value) {
		setLastUpdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ServicestoreEntriesRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.Integer value7, org.joda.time.DateTime value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ServicestoreEntriesRecord
	 */
	public ServicestoreEntriesRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES);
	}

	/**
	 * Create a detached, initialised ServicestoreEntriesRecord
	 */
	public ServicestoreEntriesRecord(java.lang.String domainId, java.lang.String userId, java.lang.String serviceId, java.lang.String context, java.lang.String key, java.lang.String value, java.lang.Integer frequency, org.joda.time.DateTime lastUpdate) {
		super(com.sonicle.webtop.core.jooq.core.tables.ServicestoreEntries.SERVICESTORE_ENTRIES);

		setValue(0, domainId);
		setValue(1, userId);
		setValue(2, serviceId);
		setValue(3, context);
		setValue(4, key);
		setValue(5, value);
		setValue(6, frequency);
		setValue(7, lastUpdate);
	}
}
