/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsDbRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.SettingsDbRecord> implements org.jooq.Record8<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1571076706;

	/**
	 * Setter for <code>core.settings_db.service_id</code>.
	 */
	public void setServiceId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.settings_db.service_id</code>.
	 */
	public java.lang.String getServiceId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>core.settings_db.key</code>.
	 */
	public void setKey(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.settings_db.key</code>.
	 */
	public java.lang.String getKey() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.settings_db.is_system</code>.
	 */
	public void setIsSystem(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.settings_db.is_system</code>.
	 */
	public java.lang.Boolean getIsSystem() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>core.settings_db.is_domain</code>.
	 */
	public void setIsDomain(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>core.settings_db.is_domain</code>.
	 */
	public java.lang.Boolean getIsDomain() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>core.settings_db.is_user</code>.
	 */
	public void setIsUser(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>core.settings_db.is_user</code>.
	 */
	public java.lang.Boolean getIsUser() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>core.settings_db.hidden</code>.
	 */
	public void setHidden(java.lang.Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>core.settings_db.hidden</code>.
	 */
	public java.lang.Boolean getHidden() {
		return (java.lang.Boolean) getValue(5);
	}

	/**
	 * Setter for <code>core.settings_db.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>core.settings_db.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>core.settings_db.help</code>.
	 */
	public void setHelp(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>core.settings_db.help</code>.
	 */
	public java.lang.String getHelp() {
		return (java.lang.String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB.SERVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB.KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB.IS_SYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB.IS_DOMAIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB.IS_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field6() {
		return com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB.HIDDEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB.HELP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getServiceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getIsSystem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getIsDomain();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getIsUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value6() {
		return getHidden();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getHelp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsDbRecord value1(java.lang.String value) {
		setServiceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsDbRecord value2(java.lang.String value) {
		setKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsDbRecord value3(java.lang.Boolean value) {
		setIsSystem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsDbRecord value4(java.lang.Boolean value) {
		setIsDomain(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsDbRecord value5(java.lang.Boolean value) {
		setIsUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsDbRecord value6(java.lang.Boolean value) {
		setHidden(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsDbRecord value7(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsDbRecord value8(java.lang.String value) {
		setHelp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsDbRecord values(java.lang.String value1, java.lang.String value2, java.lang.Boolean value3, java.lang.Boolean value4, java.lang.Boolean value5, java.lang.Boolean value6, java.lang.String value7, java.lang.String value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SettingsDbRecord
	 */
	public SettingsDbRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB);
	}

	/**
	 * Create a detached, initialised SettingsDbRecord
	 */
	public SettingsDbRecord(java.lang.String serviceId, java.lang.String key, java.lang.Boolean isSystem, java.lang.Boolean isDomain, java.lang.Boolean isUser, java.lang.Boolean hidden, java.lang.String type, java.lang.String help) {
		super(com.sonicle.webtop.core.jooq.core.tables.SettingsDb.SETTINGS_DB);

		setValue(0, serviceId);
		setValue(1, key);
		setValue(2, isSystem);
		setValue(3, isDomain);
		setValue(4, isUser);
		setValue(5, hidden);
		setValue(6, type);
		setValue(7, help);
	}
}
