/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SnoozedRemindersRecord extends org.jooq.impl.TableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.SnoozedRemindersRecord> implements org.jooq.Record10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String> {

	private static final long serialVersionUID = -33738171;

	/**
	 * Setter for <code>core.snoozed_reminders.snoozed_reminder_id</code>.
	 */
	public void setSnoozedReminderId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.snoozed_reminders.snoozed_reminder_id</code>.
	 */
	public java.lang.Integer getSnoozedReminderId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>core.snoozed_reminders.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.snoozed_reminders.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.snoozed_reminders.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.snoozed_reminders.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>core.snoozed_reminders.service_id</code>.
	 */
	public void setServiceId(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>core.snoozed_reminders.service_id</code>.
	 */
	public java.lang.String getServiceId() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>core.snoozed_reminders.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>core.snoozed_reminders.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>core.snoozed_reminders.instance_id</code>.
	 */
	public void setInstanceId(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>core.snoozed_reminders.instance_id</code>.
	 */
	public java.lang.String getInstanceId() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>core.snoozed_reminders.remind_on</code>.
	 */
	public void setRemindOn(org.joda.time.DateTime value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>core.snoozed_reminders.remind_on</code>.
	 */
	public org.joda.time.DateTime getRemindOn() {
		return (org.joda.time.DateTime) getValue(6);
	}

	/**
	 * Setter for <code>core.snoozed_reminders.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>core.snoozed_reminders.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>core.snoozed_reminders.date</code>.
	 */
	public void setDate(org.joda.time.DateTime value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>core.snoozed_reminders.date</code>.
	 */
	public org.joda.time.DateTime getDate() {
		return (org.joda.time.DateTime) getValue(8);
	}

	/**
	 * Setter for <code>core.snoozed_reminders.timezone</code>.
	 */
	public void setTimezone(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>core.snoozed_reminders.timezone</code>.
	 */
	public java.lang.String getTimezone() {
		return (java.lang.String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS.SNOOZED_REMINDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS.SERVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS.INSTANCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field7() {
		return com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS.REMIND_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field9() {
		return com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS.TIMEZONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getSnoozedReminderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getServiceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getInstanceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value7() {
		return getRemindOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value9() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getTimezone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnoozedRemindersRecord value1(java.lang.Integer value) {
		setSnoozedReminderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnoozedRemindersRecord value2(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnoozedRemindersRecord value3(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnoozedRemindersRecord value4(java.lang.String value) {
		setServiceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnoozedRemindersRecord value5(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnoozedRemindersRecord value6(java.lang.String value) {
		setInstanceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnoozedRemindersRecord value7(org.joda.time.DateTime value) {
		setRemindOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnoozedRemindersRecord value8(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnoozedRemindersRecord value9(org.joda.time.DateTime value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnoozedRemindersRecord value10(java.lang.String value) {
		setTimezone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnoozedRemindersRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, org.joda.time.DateTime value7, java.lang.String value8, org.joda.time.DateTime value9, java.lang.String value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SnoozedRemindersRecord
	 */
	public SnoozedRemindersRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS);
	}

	/**
	 * Create a detached, initialised SnoozedRemindersRecord
	 */
	public SnoozedRemindersRecord(java.lang.Integer snoozedReminderId, java.lang.String domainId, java.lang.String userId, java.lang.String serviceId, java.lang.String type, java.lang.String instanceId, org.joda.time.DateTime remindOn, java.lang.String title, org.joda.time.DateTime date, java.lang.String timezone) {
		super(com.sonicle.webtop.core.jooq.core.tables.SnoozedReminders.SNOOZED_REMINDERS);

		setValue(0, snoozedReminderId);
		setValue(1, domainId);
		setValue(2, userId);
		setValue(3, serviceId);
		setValue(4, type);
		setValue(5, instanceId);
		setValue(6, remindOn);
		setValue(7, title);
		setValue(8, date);
		setValue(9, timezone);
	}
}
