/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.core.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpgradeStatementsRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.core.jooq.core.tables.records.UpgradeStatementsRecord> implements org.jooq.Record11<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Short, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String> {

	private static final long serialVersionUID = 1348437435;

	/**
	 * Setter for <code>core.upgrade_statements.upgrade_statement_id</code>.
	 */
	public void setUpgradeStatementId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>core.upgrade_statements.upgrade_statement_id</code>.
	 */
	public java.lang.Integer getUpgradeStatementId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>core.upgrade_statements.tag</code>.
	 */
	public void setTag(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>core.upgrade_statements.tag</code>.
	 */
	public java.lang.String getTag() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>core.upgrade_statements.service_id</code>.
	 */
	public void setServiceId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>core.upgrade_statements.service_id</code>.
	 */
	public java.lang.String getServiceId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>core.upgrade_statements.sequence_no</code>.
	 */
	public void setSequenceNo(java.lang.Short value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>core.upgrade_statements.sequence_no</code>.
	 */
	public java.lang.Short getSequenceNo() {
		return (java.lang.Short) getValue(3);
	}

	/**
	 * Setter for <code>core.upgrade_statements.script_name</code>.
	 */
	public void setScriptName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>core.upgrade_statements.script_name</code>.
	 */
	public java.lang.String getScriptName() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>core.upgrade_statements.statement_type</code>.
	 */
	public void setStatementType(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>core.upgrade_statements.statement_type</code>.
	 */
	public java.lang.String getStatementType() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>core.upgrade_statements.statement_data_source</code>.
	 */
	public void setStatementDataSource(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>core.upgrade_statements.statement_data_source</code>.
	 */
	public java.lang.String getStatementDataSource() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>core.upgrade_statements.statement_body</code>.
	 */
	public void setStatementBody(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>core.upgrade_statements.statement_body</code>.
	 */
	public java.lang.String getStatementBody() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>core.upgrade_statements.run_status</code>.
	 */
	public void setRunStatus(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>core.upgrade_statements.run_status</code>.
	 */
	public java.lang.String getRunStatus() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>core.upgrade_statements.run_timestamp</code>.
	 */
	public void setRunTimestamp(org.joda.time.DateTime value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>core.upgrade_statements.run_timestamp</code>.
	 */
	public org.joda.time.DateTime getRunTimestamp() {
		return (org.joda.time.DateTime) getValue(9);
	}

	/**
	 * Setter for <code>core.upgrade_statements.run_message</code>.
	 */
	public void setRunMessage(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>core.upgrade_statements.run_message</code>.
	 */
	public java.lang.String getRunMessage() {
		return (java.lang.String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Short, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Short, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS.UPGRADE_STATEMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS.TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS.SERVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field4() {
		return com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS.SEQUENCE_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS.SCRIPT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS.STATEMENT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS.STATEMENT_DATA_SOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS.STATEMENT_BODY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS.RUN_STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field10() {
		return com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS.RUN_TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS.RUN_MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUpgradeStatementId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getServiceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value4() {
		return getSequenceNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getScriptName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getStatementType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getStatementDataSource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getStatementBody();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getRunStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value10() {
		return getRunTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getRunMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord value1(java.lang.Integer value) {
		setUpgradeStatementId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord value2(java.lang.String value) {
		setTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord value3(java.lang.String value) {
		setServiceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord value4(java.lang.Short value) {
		setSequenceNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord value5(java.lang.String value) {
		setScriptName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord value6(java.lang.String value) {
		setStatementType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord value7(java.lang.String value) {
		setStatementDataSource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord value8(java.lang.String value) {
		setStatementBody(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord value9(java.lang.String value) {
		setRunStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord value10(org.joda.time.DateTime value) {
		setRunTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord value11(java.lang.String value) {
		setRunMessage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpgradeStatementsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Short value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, org.joda.time.DateTime value10, java.lang.String value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UpgradeStatementsRecord
	 */
	public UpgradeStatementsRecord() {
		super(com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS);
	}

	/**
	 * Create a detached, initialised UpgradeStatementsRecord
	 */
	public UpgradeStatementsRecord(java.lang.Integer upgradeStatementId, java.lang.String tag, java.lang.String serviceId, java.lang.Short sequenceNo, java.lang.String scriptName, java.lang.String statementType, java.lang.String statementDataSource, java.lang.String statementBody, java.lang.String runStatus, org.joda.time.DateTime runTimestamp, java.lang.String runMessage) {
		super(com.sonicle.webtop.core.jooq.core.tables.UpgradeStatements.UPGRADE_STATEMENTS);

		setValue(0, upgradeStatementId);
		setValue(1, tag);
		setValue(2, serviceId);
		setValue(3, sequenceNo);
		setValue(4, scriptName);
		setValue(5, statementType);
		setValue(6, statementDataSource);
		setValue(7, statementBody);
		setValue(8, runStatus);
		setValue(9, runTimestamp);
		setValue(10, runMessage);
	}
}
