/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.core.jooq.config.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PecbridgeFetchersRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.core.jooq.config.tables.records.PecbridgeFetchersRecord> implements org.jooq.Record10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Short, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -375363628;

	/**
	 * Setter for <code>config.pecbridge_fetchers.fetcher_id</code>.
	 */
	public void setFetcherId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>config.pecbridge_fetchers.fetcher_id</code>.
	 */
	public java.lang.Integer getFetcherId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>config.pecbridge_fetchers.context</code>.
	 */
	public void setContext(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>config.pecbridge_fetchers.context</code>.
	 */
	public java.lang.String getContext() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>config.pecbridge_fetchers.forward_address</code>.
	 */
	public void setForwardAddress(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>config.pecbridge_fetchers.forward_address</code>.
	 */
	public java.lang.String getForwardAddress() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>config.pecbridge_fetchers.delete_on_forward</code>.
	 */
	public void setDeleteOnForward(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>config.pecbridge_fetchers.delete_on_forward</code>.
	 */
	public java.lang.Boolean getDeleteOnForward() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>config.pecbridge_fetchers.host</code>.
	 */
	public void setHost(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>config.pecbridge_fetchers.host</code>.
	 */
	public java.lang.String getHost() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>config.pecbridge_fetchers.port</code>.
	 */
	public void setPort(java.lang.Short value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>config.pecbridge_fetchers.port</code>.
	 */
	public java.lang.Short getPort() {
		return (java.lang.Short) getValue(5);
	}

	/**
	 * Setter for <code>config.pecbridge_fetchers.protocol</code>.
	 */
	public void setProtocol(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>config.pecbridge_fetchers.protocol</code>.
	 */
	public java.lang.String getProtocol() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>config.pecbridge_fetchers.username</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>config.pecbridge_fetchers.username</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>config.pecbridge_fetchers.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>config.pecbridge_fetchers.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>config.pecbridge_fetchers.webtop_profile_id</code>.
	 */
	public void setWebtopProfileId(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>config.pecbridge_fetchers.webtop_profile_id</code>.
	 */
	public java.lang.String getWebtopProfileId() {
		return (java.lang.String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Short, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Short, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS.FETCHER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS.CONTEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS.FORWARD_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS.DELETE_ON_FORWARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS.HOST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field6() {
		return com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS.PORT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS.PROTOCOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS.WEBTOP_PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getFetcherId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getContext();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getForwardAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getDeleteOnForward();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getHost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value6() {
		return getPort();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getProtocol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getWebtopProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PecbridgeFetchersRecord value1(java.lang.Integer value) {
		setFetcherId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PecbridgeFetchersRecord value2(java.lang.String value) {
		setContext(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PecbridgeFetchersRecord value3(java.lang.String value) {
		setForwardAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PecbridgeFetchersRecord value4(java.lang.Boolean value) {
		setDeleteOnForward(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PecbridgeFetchersRecord value5(java.lang.String value) {
		setHost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PecbridgeFetchersRecord value6(java.lang.Short value) {
		setPort(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PecbridgeFetchersRecord value7(java.lang.String value) {
		setProtocol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PecbridgeFetchersRecord value8(java.lang.String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PecbridgeFetchersRecord value9(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PecbridgeFetchersRecord value10(java.lang.String value) {
		setWebtopProfileId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PecbridgeFetchersRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Boolean value4, java.lang.String value5, java.lang.Short value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PecbridgeFetchersRecord
	 */
	public PecbridgeFetchersRecord() {
		super(com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS);
	}

	/**
	 * Create a detached, initialised PecbridgeFetchersRecord
	 */
	public PecbridgeFetchersRecord(java.lang.Integer fetcherId, java.lang.String context, java.lang.String forwardAddress, java.lang.Boolean deleteOnForward, java.lang.String host, java.lang.Short port, java.lang.String protocol, java.lang.String username, java.lang.String password, java.lang.String webtopProfileId) {
		super(com.sonicle.webtop.core.jooq.config.tables.PecbridgeFetchers.PECBRIDGE_FETCHERS);

		setValue(0, fetcherId);
		setValue(1, context);
		setValue(2, forwardAddress);
		setValue(3, deleteOnForward);
		setValue(4, host);
		setValue(5, port);
		setValue(6, protocol);
		setValue(7, username);
		setValue(8, password);
		setValue(9, webtopProfileId);
	}
}
